import Mathlib
import EtingofRepresentationTheory.Chapter5.Theorem5_22_1
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2_Irreducible

/-!
# Specht Module Simplicity over ℚ

We prove that the Specht module V_λ = ℚ[S_n]·c_λ is a simple (irreducible) left
ℚ[S_n]-module. The proof derives the sandwich property over ℚ from the ℂ version
(via base change through ℤ) and then follows the same irreducibility argument.

## Main results

* `SpechtModuleK` — the left ideal k[S_n]·c_λ over a general commutative ring k
* `YoungSymmetrizerZ_sandwich_basis` — c_ℤ * of(σ) * c_ℤ is proportional to c_ℤ
* `SpechtModuleK_isSimpleModule` — ℚ[S_n]·c_λ is simple
-/

noncomputable section

namespace Etingof

private abbrev G' (n : ℕ) := Equiv.Perm (Fin n)
private abbrev AQ (n : ℕ) := MonoidAlgebra ℚ (G' n)

/-- The Specht module V_λ = k[S_n]·c_λ, the left ideal of the group algebra
generated by the Young symmetrizer, over a general commutative ring k. -/
def SpechtModuleK (k : Type*) [CommRing k] (n : ℕ) (la : Nat.Partition n) :
    Submodule (MonoidAlgebra k (Equiv.Perm (Fin n))) (MonoidAlgebra k (Equiv.Perm (Fin n))) :=
  Submodule.span _ {YoungSymmetrizerK k n la}

/-! ### Sandwich property via base change from ℤ -/

/-- The ring hom ℤ[S_n] → ℂ[S_n] is injective (since ℤ → ℂ is injective). -/
private lemma mapRangeRingHom_int_complex_injective (n : ℕ) :
    Function.Injective (MonoidAlgebra.mapRangeRingHom (Equiv.Perm (Fin n))
      (Int.castRingHom ℂ)) := by
  rw [MonoidAlgebra.coe_mapRangeRingHom]
  exact Finsupp.mapRange_injective _ (map_zero _) Int.cast_injective

/-- For each σ, the element c_ℤ * of(σ) * c_ℤ in ℤ[S_n] is proportional to c_ℤ.

The proportionality constant is β(σ) = (c_ℤ * of(σ) * c_ℤ)(1).

Proof: Over ℂ, Lemma 5.13.1 gives a * x * b = ℓ(x) • c, hence c * x * c = f(x) • c.
Since c_ℂ = mapRange(c_ℤ) and c_ℤ(1) = 1, evaluating at 1 shows f(σ) ∈ ℤ.
By injectivity of ℤ → ℂ, the identity holds over ℤ. -/
theorem YoungSymmetrizerZ_sandwich_basis (n : ℕ) (la : Nat.Partition n)
    (σ : Equiv.Perm (Fin n)) :
    YoungSymmetrizerZ n la * MonoidAlgebra.of ℤ _ σ * YoungSymmetrizerZ n la =
      (YoungSymmetrizerZ n la * MonoidAlgebra.of ℤ _ σ * YoungSymmetrizerZ n la) 1 •
        YoungSymmetrizerZ n la := by
  set φ := MonoidAlgebra.mapRangeRingHom (Equiv.Perm (Fin n)) (Int.castRingHom ℂ)
  set cZ := YoungSymmetrizerZ n la
  set y := cZ * MonoidAlgebra.of ℤ _ σ * cZ
  -- φ is injective
  have hφ_inj := mapRangeRingHom_int_complex_injective n
  -- φ preserves c and of
  have hφc : φ cZ = YoungSymmetrizer n la :=
    (YoungSymmetrizer_eq_mapRange n la).symm
  have hφσ : φ (MonoidAlgebra.of ℤ _ σ) = MonoidAlgebra.of ℂ _ σ := by
    change MonoidAlgebra.mapRangeRingHom _ _ (Finsupp.single σ 1) = Finsupp.single σ 1
    rw [MonoidAlgebra.mapRangeRingHom_single, map_one]
  -- Over ℂ: b * x * a = ℓ(x) • c (Lemma 5.13.1)
  obtain ⟨ℓ, hℓ⟩ := Etingof.Lemma5_13_1 n la
  -- The sandwich for c: c * x * c = ℓ(a * (x * b)) • c
  have h_sandwich : ∀ x,
      YoungSymmetrizer n la * x * YoungSymmetrizer n la =
        ℓ (RowSymmetrizer n la * (x * ColumnAntisymmetrizer n la)) •
          YoungSymmetrizer n la := by
    intro x
    change ColumnAntisymmetrizer n la * RowSymmetrizer n la * x *
        (ColumnAntisymmetrizer n la * RowSymmetrizer n la) = _
    rw [show ColumnAntisymmetrizer n la * RowSymmetrizer n la * x *
          (ColumnAntisymmetrizer n la * RowSymmetrizer n la) =
        ColumnAntisymmetrizer n la * (RowSymmetrizer n la * (x * ColumnAntisymmetrizer n la)) *
          RowSymmetrizer n la from by simp only [mul_assoc]]
    rw [hℓ]
  -- φ(y) = f_val • φ(cZ) over ℂ
  set f_val := ℓ (RowSymmetrizer n la *
    (MonoidAlgebra.of ℂ _ σ * ColumnAntisymmetrizer n la))
  have h_ℂ : φ y = f_val • φ cZ := by
    change φ (cZ * MonoidAlgebra.of ℤ _ σ * cZ) = _ • φ cZ
    rw [map_mul, map_mul, hφc, hφσ]
    exact h_sandwich (MonoidAlgebra.of ℂ _ σ)
  -- c_ℤ(1) = 1
  have hcZ1 : cZ 1 = 1 := YoungSymmetrizerZ_apply_one n la
  -- f_val = (y 1 : ℂ), so f_val ∈ ℤ (cast to ℂ)
  have hf_eq : f_val = ((y 1 : ℤ) : ℂ) := by
    -- Evaluate h_ℂ at identity
    have h1 : (f_val • φ cZ) (1 : Equiv.Perm (Fin n)) = f_val := by
      rw [Finsupp.smul_apply, smul_eq_mul]
      change f_val * ((cZ 1 : ℤ) : ℂ) = f_val
      rw [hcZ1, Int.cast_one, mul_one]
    have h2 : (φ y) (1 : Equiv.Perm (Fin n)) = ((y 1 : ℤ) : ℂ) := by
      rw [MonoidAlgebra.coe_mapRangeRingHom]; rfl
    calc f_val = (f_val • φ cZ) 1 := h1.symm
      _ = (φ y) 1 := by rw [h_ℂ]
      _ = ((y 1 : ℤ) : ℂ) := h2
  -- φ(y) = φ(y 1 • cZ), so y = y 1 • cZ by injectivity
  apply hφ_inj
  rw [h_ℂ, hf_eq, map_zsmul, Int.cast_smul_eq_zsmul ℂ]

/-- The Young symmetrizer over ℚ satisfies the sandwich property:
c * x * c = f(x) • c for a linear functional f. -/
theorem YoungSymmetrizerK_sandwich_ℚ (n : ℕ) (la : Nat.Partition n) :
    ∃ f : AQ n →ₗ[ℚ] ℚ, ∀ x,
      YoungSymmetrizerK ℚ n la * x * YoungSymmetrizerK ℚ n la =
        f x • YoungSymmetrizerK ℚ n la := by
  set ψ := MonoidAlgebra.mapRangeRingHom (Equiv.Perm (Fin n)) (Int.castRingHom ℚ)
  set cZ := YoungSymmetrizerZ n la
  set cQ := YoungSymmetrizerK ℚ n la
  have hψc : ψ cZ = cQ := (YoungSymmetrizerK_eq_mapRange ℚ n la).symm
  -- For each basis element σ, get the proportionality constant from ℤ
  have basis_prop : ∀ σ : Equiv.Perm (Fin n), ∃ β : ℤ,
      cQ * MonoidAlgebra.of ℚ _ σ * cQ = (β : ℚ) • cQ := by
    intro σ
    set β := (cZ * MonoidAlgebra.of ℤ _ σ * cZ) 1
    refine ⟨β, ?_⟩
    have hψσ : ψ (MonoidAlgebra.of ℤ _ σ) = MonoidAlgebra.of ℚ _ σ := by
      change MonoidAlgebra.mapRangeRingHom _ _ (Finsupp.single σ 1) = Finsupp.single σ 1
      rw [MonoidAlgebra.mapRangeRingHom_single, map_one]
    have hZ := YoungSymmetrizerZ_sandwich_basis n la σ
    calc cQ * MonoidAlgebra.of ℚ _ σ * cQ
        = ψ cZ * ψ (MonoidAlgebra.of ℤ _ σ) * ψ cZ := by rw [hψc, hψσ]
      _ = ψ (cZ * MonoidAlgebra.of ℤ _ σ * cZ) := by rw [map_mul, map_mul]
      _ = ψ (β • cZ) := by rw [hZ]
      _ = (β : ℚ) • cQ := by
          rw [map_zsmul, hψc]; rfl
  -- Build the linear functional
  choose β hβ using basis_prop
  let f : AQ n →ₗ[ℚ] ℚ :=
    Finsupp.lsum ℚ (fun σ => (β σ : ℚ) • (LinearMap.id : ℚ →ₗ[ℚ] ℚ))
  refine ⟨f, fun x => ?_⟩
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy =>
    simp only [mul_add, add_mul, map_add, add_smul]
    exact congr_arg₂ (· + ·) hx hy
  | single σ r =>
    have hf_single : f (Finsupp.single σ r) = (β σ : ℚ) * r := by
      change (Finsupp.lsum ℚ (fun σ => (β σ : ℚ) • (LinearMap.id : ℚ →ₗ[ℚ] ℚ)))
        (Finsupp.single σ r) = _
      rw [Finsupp.lsum_single, LinearMap.smul_apply, LinearMap.id_apply, smul_eq_mul]
    have hsingle : (Finsupp.single σ r : MonoidAlgebra ℚ _) = r • MonoidAlgebra.of ℚ _ σ := by
      simp [MonoidAlgebra.of_apply, mul_one]
    conv_lhs => rw [hsingle]
    rw [Algebra.mul_smul_comm, Algebra.smul_mul_assoc, hβ, smul_smul, hf_single, mul_comm]

/-! ### Helper lemmas for simplicity proof -/

/-- The coefficient of the identity in YoungSymmetrizerK ℚ is 1. -/
private lemma YoungSymmetrizerK_ℚ_apply_one (n : ℕ) (la : Nat.Partition n) :
    YoungSymmetrizerK ℚ n la 1 = 1 := by
  rw [YoungSymmetrizerK_eq_mapRange ℚ n la]
  simp [MonoidAlgebra.mapRangeRingHom_apply, YoungSymmetrizerZ_apply_one]

/-- YoungSymmetrizerK ℚ is nonzero. -/
private lemma YoungSymmetrizerK_ℚ_ne_zero (n : ℕ) (la : Nat.Partition n) :
    YoungSymmetrizerK ℚ n la ≠ 0 := by
  intro h
  have := YoungSymmetrizerK_ℚ_apply_one n la
  rw [h, Finsupp.zero_apply] at this
  exact zero_ne_one this

/-! ### Simplicity of the ℚ-Specht module -/

instance neZero_card_perm_ℚ (n : ℕ) : NeZero (Nat.card (G' n) : ℚ) :=
  ⟨by exact_mod_cast Nat.card_pos.ne'⟩

/-- The Specht module V_λ = ℚ[S_n]·c_λ is a simple (irreducible) left ℚ[S_n]-module. -/
theorem SpechtModuleK_isSimpleModule (n : ℕ) (la : Nat.Partition n) :
    IsSimpleModule (AQ n) (SpechtModuleK ℚ n la) := by
  rw [isSimpleModule_iff_isAtom]
  obtain ⟨α, hα_eq⟩ := YoungSymmetrizerK_sq_scalar ℚ n la
  have hα_ne : α ≠ 0 := YoungSymmetrizerK_sq_scalar_ne_zero n la α hα_eq
  obtain ⟨f, hf⟩ := YoungSymmetrizerK_sandwich_ℚ n la
  set c := YoungSymmetrizerK ℚ n la with hc_def
  refine ⟨?_, ?_⟩
  · -- SpechtModuleK ≠ ⊥
    intro h
    have hc_zero : (c : AQ n) = 0 :=
      (Submodule.mem_bot (R := AQ n)).mp (h ▸ Submodule.subset_span rfl)
    exact YoungSymmetrizerK_ℚ_ne_zero n la hc_zero
  · -- ∀ N < SpechtModuleK, N = ⊥
    intro N hN
    by_contra hN_ne_bot
    have hN_le := le_of_lt hN
    suffices c ∈ N by
      exact ne_of_lt hN
        (le_antisymm hN_le (Submodule.span_le.mpr (Set.singleton_subset_iff.mpr this)))
    obtain ⟨P, hP⟩ := (inferInstance : IsSemisimpleModule (AQ n) (AQ n)).exists_isCompl N
    obtain ⟨n₀, hn₀, p₀, hp₀, hc_eq⟩ := Submodule.mem_sup.mp
      (show c ∈ N ⊔ P from hP.sup_eq_top ▸ Submodule.mem_top)
    obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp
      (show n₀ ∈ SpechtModuleK ℚ n la from hN_le hn₀)
    have hcn₀ : c * n₀ = f a • c := by
      rw [← ha]; change c * (a * c) = _; rw [← mul_assoc]; exact hf a
    have hcn₀_N : c * n₀ ∈ N := N.smul_mem _ hn₀
    by_cases hfa : f a = 0
    · rw [hfa, zero_smul] at hcn₀
      have hcc_cp₀ : c * c = c * p₀ := by
        calc c * c = c * (n₀ + p₀) := by rw [hc_eq]
          _ = c * n₀ + c * p₀ := mul_add _ _ _
          _ = c * p₀ := by rw [hcn₀, zero_add]
      have hαc_P : α • c ∈ P := by rw [← hα_eq, hcc_cp₀]; exact P.smul_mem _ hp₀
      have h1 : α • n₀ ∈ N := Submodule.smul_of_tower_mem N α hn₀
      have h2 : α • n₀ ∈ P := by
        rw [show α • n₀ = α • c - α • p₀ from by rw [← hc_eq, smul_add, add_sub_cancel_right]]
        exact P.sub_mem hαc_P (Submodule.smul_of_tower_mem P α hp₀)
      have h3 : α • n₀ = 0 :=
        (Submodule.mem_bot (R := AQ n)).mp (hP.inf_eq_bot ▸ Submodule.mem_inf.mpr ⟨h1, h2⟩)
      have hn₀_zero : n₀ = 0 := (smul_eq_zero.mp h3).resolve_left hα_ne
      exfalso; apply hN_ne_bot; rw [eq_bot_iff]; intro x hx
      have hc_P : c ∈ P := by rw [← hc_eq, hn₀_zero, zero_add]; exact hp₀
      have hV_le_P : SpechtModuleK ℚ n la ≤ P :=
        Submodule.span_le.mpr (Set.singleton_subset_iff.mpr hc_P)
      exact (Submodule.mem_bot (R := AQ n)).mpr
        ((Submodule.mem_bot (R := AQ n)).mp
          (hP.inf_eq_bot ▸ Submodule.mem_inf.mpr ⟨hx, hV_le_P (hN_le hx)⟩))
    · rw [hcn₀] at hcn₀_N
      rw [show c = (f a)⁻¹ • (f a • c) from by rw [inv_smul_smul₀ hfa]]
      exact Submodule.smul_of_tower_mem N (f a)⁻¹ hcn₀_N

end Etingof
