import Mathlib.RingTheory.Jacobson.Ideal
import Mathlib.RingTheory.Polynomial.Quotient

/-!
# Example 3.5.6: Radicals of k[x]/(x^n) and Upper Triangular Matrices

1. Let A = k[x]/(xⁿ). This algebra has a unique irreducible representation, which is a
   1-dimensional space k, in which x acts by zero. So Rad(A) is the ideal (x).

2. Let A be the algebra of upper triangular n × n matrices. The irreducible representations
   are Vᵢ, i = 1, …, n, which are 1-dimensional, and any matrix x acts by xᵢᵢ. So Rad(A)
   is the ideal of strictly upper triangular matrices.
-/

/-- The radical of k[x]/(xⁿ) is the ideal generated by x.
Etingof Example 3.5.6(1). -/
theorem Etingof.radical_truncated_polynomial (k : Type*) [Field k] (n : ℕ) (hn : 0 < n) :
    -- Rad(k[x]/(xⁿ)) = (x̄) where x̄ is the image of x
    True := by
  sorry

/-- The radical of the algebra of upper triangular matrices is the ideal of strictly
upper triangular matrices. Etingof Example 3.5.6(2). -/
theorem Etingof.radical_upper_triangular (k : Type*) [Field k] (n : ℕ) :
    -- Rad(UpperTriangular_n(k)) = StrictlyUpperTriangular_n(k)
    True := by
  sorry
