import Mathlib.RingTheory.Jacobson.Radical
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Mathlib.RingTheory.Nilpotent.Lemmas
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.Polynomial.Ideal
import Mathlib.LinearAlgebra.Matrix.Block

/-!
# Example 3.5.6: Radicals of k[x]/(x^n) and Upper Triangular Matrices

1. Let A = k[x]/(xⁿ). This algebra has a unique irreducible representation, which is a
   1-dimensional space k, in which x acts by zero. So Rad(A) is the ideal (x).

2. Let A be the algebra of upper triangular n × n matrices. The irreducible representations
   are Vᵢ, i = 1, …, n, which are 1-dimensional, and any matrix x acts by xᵢᵢ. So Rad(A)
   is the ideal of strictly upper triangular matrices.
-/

open Polynomial

/-- The radical of k[x]/(xⁿ) is the ideal generated by x.
Etingof Example 3.5.6(1). -/
theorem Etingof.radical_truncated_polynomial (k : Type*) [Field k] (n : ℕ) (hn : 0 < n) :
    Ring.jacobson (AdjoinRoot (X ^ n : k[X])) =
      Ideal.span {AdjoinRoot.root (X ^ n : k[X])} := by
  set f := (X ^ n : k[X])
  set A := AdjoinRoot f
  set r := AdjoinRoot.root f
  -- Define the evaluation-at-zero map
  have heval : f.eval₂ (RingHom.id k) 0 = 0 := by simp [f, eval₂_pow, eval₂_X, zero_pow hn.ne']
  set ev₀ : A →+* k := AdjoinRoot.lift (RingHom.id k) 0 heval
  -- Direction ≥: root is nilpotent → root ∈ nilradical ≤ jacobson
  have hr_nil : IsNilpotent r := ⟨n, by
    change (AdjoinRoot.mk f X) ^ n = 0
    rw [← map_pow, AdjoinRoot.mk_self]⟩
  have h_ge : Ideal.span {r} ≤ Ring.jacobson A := by
    rw [Ideal.span_le]
    intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst hx
    exact nilradical_le_jacobson A (mem_nilradical.mpr hr_nil)
  -- Direction ≤: Ideal.span {r} is maximal, so jacobson ≤ it
  have hmax : (Ideal.span {r}).IsMaximal := by
    have hev_surj : Function.Surjective ev₀ := by
      intro c; exact ⟨AdjoinRoot.of f c, AdjoinRoot.lift_of heval⟩
    suffices hker : RingHom.ker ev₀ = Ideal.span {r} from
      hker ▸ RingHom.ker_isMaximal_of_surjective ev₀ hev_surj
    change RingHom.ker (Ideal.Quotient.lift _ _ _) = _
    rw [Ideal.ker_quotient_lift]
    have hker_eval : RingHom.ker (Polynomial.eval₂RingHom (RingHom.id k) (0 : k)) =
        Ideal.span {X - C 0} := by
      change RingHom.ker (evalRingHom 0) = _
      exact ker_evalRingHom 0
    rw [hker_eval]
    simp only [map_zero, sub_zero]
    rw [Ideal.map_span, Set.image_singleton]
    rfl
  exact le_antisymm (Ring.jacobson_le_of_isMaximal (Ideal.span {r})) h_ge

/-- The subalgebra of upper triangular matrices in Mₙ(k). -/
def Etingof.upperTriangularSubalgebra (k : Type*) [Field k] (n : ℕ) :
    Subalgebra k (Matrix (Fin n) (Fin n) k) where
  carrier := {M | ∀ i j, j < i → M i j = 0}
  mul_mem' {a b} ha hb i j hij := by
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hlj : l < i
    · simp [ha i l hlj]
    · push_neg at hlj
      simp [hb l j (lt_of_lt_of_le hij hlj)]
  one_mem' i j hij := by
    simp [Matrix.one_apply]
    intro h
    exact absurd (h ▸ hij) (lt_irrefl _)
  add_mem' {a b} ha hb i j hij := by simp [ha i j hij, hb i j hij]
  zero_mem' _ _ _ := by simp
  algebraMap_mem' r i j hij := by
    simp [Algebra.algebraMap_eq_smul_one, Matrix.one_apply]
    intro h
    exact absurd (h ▸ hij) (lt_irrefl _)

/-- The ideal of strictly upper triangular matrices within the upper triangular subalgebra. -/
def Etingof.strictlyUpperTriangularIdeal (k : Type*) [Field k] (n : ℕ) :
    Ideal (↥(Etingof.upperTriangularSubalgebra k n)) where
  carrier := {M | ∀ i j, j ≤ i → (M : Matrix (Fin n) (Fin n) k) i j = 0}
  add_mem' {a b} ha hb i j hij := by simp [ha i j hij, hb i j hij]
  zero_mem' _ _ _ := by simp
  smul_mem' c x hx i j hij := by
    have : (c • x).val = (c : Matrix (Fin n) (Fin n) k) * (x : Matrix (Fin n) (Fin n) k) := rfl
    rw [this, Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hli : i ≤ l
    · simp [hx l j (le_trans hij hli)]
    · push_neg at hli
      simp [c.2 i l hli]

instance Etingof.strictlyUpperTriangularIdeal.isTwoSided (k : Type*) [Field k] (n : ℕ) :
    (Etingof.strictlyUpperTriangularIdeal k n).IsTwoSided where
  mul_mem_of_left b ha i j hij := by
    have hmul : ∀ (a b : ↥(Etingof.upperTriangularSubalgebra k n)),
        (a * b).val = (a : Matrix (Fin n) (Fin n) k) * (b : Matrix (Fin n) (Fin n) k) :=
      fun _ _ => rfl
    rw [hmul]
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hli : l ≤ i
    · simp [ha i l hli]
    · push_neg at hli
      simp [b.2 l j (lt_of_le_of_lt hij hli)]

/-- The radical of the algebra of upper triangular n × n matrices is the ideal of strictly
upper triangular matrices. Etingof Example 3.5.6(2). -/
theorem Etingof.radical_upper_triangular (k : Type*) [Field k] (n : ℕ) :
    Ring.jacobson (↥(Etingof.upperTriangularSubalgebra k n)) =
      Etingof.strictlyUpperTriangularIdeal k n := by
  set S := Etingof.upperTriangularSubalgebra k n
  set I := Etingof.strictlyUpperTriangularIdeal k n
  apply le_antisymm
  · -- ≤: jacobson ≤ I (via diagonal extraction homomorphisms)
    intro x hx
    show ∀ i j : Fin n, j ≤ i → (x : Matrix (Fin n) (Fin n) k) i j = 0
    intro i j hij
    rcases hij.eq_or_lt with rfl | hlt
    · -- j = i: show x.val j j = 0 via diagonal extraction ring hom to k
      let π : ↥S →+* k :=
        { toFun := fun M => M.val j j
          map_one' := by simp
          map_mul' := fun a b => by
            change (a.1 * b.1) j j = a.1 j j * b.1 j j
            simp only [Matrix.mul_apply]
            apply Finset.sum_eq_single j
            · intro l _ hli
              rcases lt_or_gt_of_ne hli with h | h
              · simp [a.2 j l h]
              · simp [b.2 l j h]
            · intro h; exact absurd (Finset.mem_univ j) h
          map_zero' := by simp
          map_add' := fun a b => by simp }
      have π_surj : Function.Surjective π := by
        intro c
        exact ⟨⟨Matrix.diagonal (Function.update 0 j c), fun p q hpq => by
          simp [Matrix.diagonal_apply, Function.update_apply]
          intro h; exact absurd (h ▸ hpq) (lt_irrefl _)⟩, by
          simp [π]⟩
      haveI : (RingHom.ker π).IsMaximal := RingHom.ker_isMaximal_of_surjective _ π_surj
      exact Ring.jacobson_le_of_isMaximal (RingHom.ker π) hx
    · -- j < i: upper triangular property
      exact x.2 i j hlt
  · -- ≥: I ≤ jacobson (strictly upper triangular elements are nilpotent)
    -- Helper: elements of I are nilpotent (z^n = 0)
    have nil_of_mem : ∀ z : ↥S, z ∈ I → IsNilpotent z := by
      intro z hz
      refine ⟨n, Subtype.ext ?_⟩
      show ((z ^ n : ↥S) : Matrix (Fin n) (Fin n) k) = 0
      ext p q; simp only [Matrix.zero_apply]
      suffices ∀ (m : ℕ) (p q : Fin n), (q : ℕ) < (p : ℕ) + m →
          ((z ^ m : ↥S) : Matrix (Fin n) (Fin n) k) p q = 0 by
        exact this n p q (by omega)
      intro m; induction m with
      | zero =>
        intro p q h; simp only [pow_zero]
        show (1 : Matrix (Fin n) (Fin n) k) p q = 0
        rw [Matrix.one_apply, if_neg (Fin.ne_of_val_ne (by omega))]
      | succ m ih =>
        intro p q h
        have : ((z ^ (m + 1) : ↥S) : Matrix _ _ k) p q =
            ∑ l, ((z ^ m : ↥S) : Matrix _ _ k) p l * z.val l q := by
          show ((z ^ m).val * z.val) p q = _
          rw [Matrix.mul_apply]
        rw [this]
        apply Finset.sum_eq_zero; intro l _
        by_cases hl : (l : ℕ) < (p : ℕ) + m
        · simp [ih p l hl]
        · push_neg at hl; simp [hz l q (show (q : ℕ) ≤ (l : ℕ) by omega)]
    -- x ∈ I → x ∈ every maximal ideal → x ∈ jacobson
    rw [Ring.jacobson_eq_sInf_isMaximal]
    intro x hx
    simp only [Ideal.mem_sInf, Set.mem_setOf_eq]
    intro J hJ
    -- If x ∉ J, then J < J ⊔ Ideal.span {x}, so J ⊔ Ideal.span {x} = ⊤ by maximality.
    -- Then 1 = a + r*x with a ∈ J. Since r*x ∈ I is nilpotent, a = 1-r*x is a unit.
    -- Unit in J → J = ⊤, contradicting maximality.
    by_contra hxJ
    apply hJ.ne_top
    have hlt : J < J ⊔ Ideal.span {x} := by
      refine lt_of_le_of_ne le_sup_left fun heq => hxJ ?_
      exact heq ▸ SetLike.le_def.mp le_sup_right (Ideal.mem_span_singleton_self x)
    have htop := hJ.1.2 _ hlt
    rw [Ideal.eq_top_iff_one] at htop
    obtain ⟨a, ha, b, hb, hab⟩ := Submodule.mem_sup.mp htop
    obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp hb
    have ha_eq : a = 1 - r * x := (eq_sub_iff_add_eq).mpr hab
    exact J.eq_top_of_isUnit_mem ha (ha_eq ▸ (nil_of_mem _ (I.smul_mem r hx)).isUnit_one_sub)
