import Mathlib

/-!
# Lemma 5.18.3: Symmetric Power Generation

Two key generation results:

(i) S^n U (the n-th symmetric power) is spanned by elements of the form
    u ⊗ u ⊗ ... ⊗ u (n times) for u ∈ U. This follows from the fact that
    S^n U is an irreducible GL(U)-module (equivalently, by polarization).

(ii) S^n A (for an algebra A) is generated as an algebra by elements Δ_n(a)
     for a ∈ A, where Δ_n(a) = a⊗1⊗...⊗1 + 1⊗a⊗...⊗1 + ... + 1⊗...⊗1⊗a.
     This follows from the fundamental theorem of symmetric functions.

## Mathlib correspondence

- `SymmetricPower` for S^n U (quotient of `PiTensorProduct` by permutations)
- `SymmetricPower.tprod` for the canonical multilinear map to the symmetric power
- `Submodule.span` for module generation
- The algebra structure on S^n A is not yet in Mathlib (listed as TODO).
  Part (ii) is stated in terms of the subalgebra generated by diagonal operators
  in End(V^⊗n), which captures the same content in the representation-theoretic
  context where this lemma is applied.
-/

open scoped TensorProduct

namespace Etingof.Lemma5_18_3

section Span

variable (k : Type) [Field k]
  (U : Type*) [AddCommGroup U] [Module k U] [Module.Finite k U]
  (n : ℕ)

/-- The set of n-fold diagonal symmetric tensors u^⊗n for u ∈ U.
These are elements of S^n U of the form u ⊗ u ⊗ ... ⊗ u (n times). -/
def diagonalTensors : Set (Sym[k]^n U) :=
  Set.range (fun u : U => SymmetricPower.tprod k (fun (_ : Fin n) => u))

/-- Alternating sum of (-1)^|S| over subsets of a nonempty finset is zero.
This is the fundamental Möbius identity on the boolean lattice. -/
private lemma sum_powerset_neg_one_pow_card_eq_zero
    {α : Type*} {x : Finset α} (hx : x.Nonempty) :
    (∑ m ∈ x.powerset, (-1 : k) ^ m.card) = 0 := by
  have hZ := Finset.sum_powerset_neg_one_pow_card_of_nonempty hx
  -- Cast the ℤ identity to k
  have : (∑ m ∈ x.powerset, (-1 : k) ^ m.card) =
      ((∑ m ∈ x.powerset, (-1 : ℤ) ^ m.card : ℤ) : k) := by
    rw [Int.cast_sum]
    congr 1; ext m
    simp [Int.cast_pow]
  rw [this, hZ, Int.cast_zero]

/-- The alternating sum over supersets of T in Finset.univ equals 1 if T = univ, 0 otherwise.
Key lemma for the polarization identity. -/
private lemma alternating_superset_sum
    (T : Finset (Fin n)) :
    (∑ S ∈ (Finset.univ : Finset (Fin n)).powerset.filter (fun S => T ⊆ S),
      (-1 : k) ^ (n - S.card)) =
    if T = Finset.univ then 1 else 0 := by
  classical
  -- Biject {S | T ⊆ S ⊆ univ} ↔ {T' | T' ⊆ univ \ T} via S ↦ S \ T
  -- Under this bijection: n - |S| = n - |T| - |T'| = |univ \ T| - |T'|
  -- And the sum becomes ∑_{T' ⊆ univ\T} (-1)^{|univ\T| - |T'|}
  -- For T = univ: univ \ T = ∅, so the only T' is ∅, giving (-1)^0 = 1
  -- For T ≠ univ: univ \ T is nonempty, and the sum = (-1)^{|univ\T|} * ∑ (-1)^{|T'|} = 0
  split_ifs with hT
  · -- Case T = univ: only superset is univ itself
    subst hT
    have : Finset.univ.powerset.filter (fun S => Finset.univ ⊆ S) =
        {(Finset.univ : Finset (Fin n))} := by
      ext S; simp [Finset.univ_subset_iff]
    rw [this, Finset.sum_singleton, Finset.card_univ, Fintype.card_fin, Nat.sub_self, pow_zero]
  · -- Case T ≠ univ: use Möbius identity
    have hC : (Finset.univ \ T).Nonempty := by
      rw [Finset.sdiff_nonempty]
      exact fun h => hT (Finset.univ_subset_iff.mp h)
    -- Biject {S | T ⊆ S ⊆ univ} ↔ powerset(univ \ T) via S ↦ S \ T, inverse T' ↦ T' ∪ T
    rw [show ∑ S ∈ Finset.univ.powerset.filter (fun S => T ⊆ S),
          (-1 : k) ^ (n - S.card) =
        ∑ T' ∈ (Finset.univ \ T).powerset,
          (-1 : k) ^ ((Finset.univ \ T).card - T'.card) from by
      apply Finset.sum_nbij' (· \ T) (· ∪ T)
      · -- hi: S \ T ∈ powerset(univ \ T)
        intro S hS
        simp only [Finset.mem_filter, Finset.mem_powerset] at hS ⊢
        exact Finset.sdiff_subset_sdiff hS.1 (Finset.Subset.refl T)
      · -- hj: T' ∪ T ∈ filtered set
        intro T' hT'
        simp only [Finset.mem_powerset] at hT'
        simp only [Finset.mem_filter, Finset.mem_powerset]
        exact ⟨Finset.union_subset (hT'.trans Finset.sdiff_subset) (Finset.subset_univ T),
               Finset.subset_union_right⟩
      · -- left_inv: (S \ T) ∪ T = S
        intro S hS
        simp only [Finset.mem_filter, Finset.mem_powerset] at hS
        exact Finset.sdiff_union_of_subset hS.2
      · -- right_inv: (T' ∪ T) \ T = T'
        intro T' hT'
        simp only [Finset.mem_powerset] at hT'
        rw [Finset.union_sdiff_right, Finset.sdiff_eq_self_of_disjoint]
        exact Finset.disjoint_of_subset_left hT' disjoint_sdiff_self_left
      · -- h: summands match — need n - |S| = |C| - |S \ T| where C = univ \ T
        intro S hS
        simp only [Finset.mem_filter, Finset.mem_powerset] at hS
        congr 1
        -- Use card_sdiff_add_card to avoid ℕ subtraction issues
        have h1 : (S \ T).card + T.card = S.card :=
          Finset.card_sdiff_add_card_eq_card hS.2
        have h2 : ((Finset.univ : Finset (Fin n)) \ T).card + T.card =
            (Finset.univ : Finset (Fin n)).card :=
          Finset.card_sdiff_add_card_eq_card (Finset.subset_univ T)
        have h3 : S.card ≤ (Finset.univ : Finset (Fin n)).card :=
          Finset.card_le_card hS.1
        have h4 : (S \ T).card ≤ ((Finset.univ : Finset (Fin n)) \ T).card :=
          Finset.card_le_card (Finset.sdiff_subset_sdiff hS.1 (Finset.Subset.refl T))
        simp only [Finset.card_univ, Fintype.card_fin] at h2 h3
        omega]
    -- Now need: ∑ T' ∈ C.powerset, (-1)^(C.card - T'.card) = 0
    -- Factor: (-1)^(a-b) = (-1)^a * (-1)^b since (-1)^2 = 1
    set C := Finset.univ \ T with hCdef
    have factor : ∀ T' ∈ C.powerset, (-1 : k) ^ (C.card - T'.card) =
        (-1 : k) ^ C.card * (-1 : k) ^ T'.card := by
      intro T' hT'
      simp only [Finset.mem_powerset] at hT'
      have hle := Finset.card_le_card hT'
      have hmul : (-1 : k) ^ (C.card - T'.card) * (-1 : k) ^ T'.card =
          (-1 : k) ^ C.card := by
        rw [← pow_add, Nat.sub_add_cancel hle]
      have hsq : (-1 : k) ^ T'.card * (-1 : k) ^ T'.card = 1 := by
        rw [← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow]
      calc (-1 : k) ^ (C.card - T'.card)
          = (-1 : k) ^ (C.card - T'.card) * 1 := (mul_one _).symm
        _ = (-1 : k) ^ (C.card - T'.card) *
            ((-1 : k) ^ T'.card * (-1 : k) ^ T'.card) := by rw [hsq]
        _ = (-1 : k) ^ (C.card - T'.card) * (-1 : k) ^ T'.card *
            (-1 : k) ^ T'.card := by rw [mul_assoc]
        _ = (-1 : k) ^ C.card * (-1 : k) ^ T'.card := by rw [hmul]
    rw [Finset.sum_congr rfl factor, ← Finset.mul_sum]
    rw [sum_powerset_neg_one_pow_card_eq_zero (k := k) hC, mul_zero]

/-- The polarization identity for symmetric tensors.

n! • tprod(f) = ∑_{S ⊆ Fin n} (-1)^{n-|S|} • (∑_{i∈S} f i)^⊗n

This expresses a general pure symmetric tensor as a ℤ-linear combination
of diagonal tensors (times n!). -/
private lemma polarization_eq [CharZero k] (f : Fin n → U) :
    (n.factorial : k) • SymmetricPower.tprod k f =
      ∑ S ∈ (Finset.univ : Finset (Fin n)).powerset,
        ((-1 : k) ^ (n - S.card)) • SymmetricPower.tprod k (fun _ => ∑ i ∈ S, f i) := by
  classical
  -- Step 1: Expand each tprod(const(∑ f i)) using multilinearity, distribute smul
  conv_rhs =>
    arg 2; ext S
    rw [show (-1 : k) ^ (n - S.card) • SymmetricPower.tprod k (fun _ => ∑ i ∈ S, f i) =
        ∑ r ∈ Fintype.piFinset (fun _ : Fin n => S),
          (-1 : k) ^ (n - S.card) • (SymmetricPower.tprod k) (fun i => f (r i)) by
      rw [MultilinearMap.map_sum_finset (SymmetricPower.tprod k) (fun _ => f) (fun _ => S)]
      rw [Finset.smul_sum]]
  -- Step 2: Swap the order of summation using sum_comm'
  rw [Finset.sum_comm'
    (s' := fun r => Finset.univ.powerset.filter (fun S => ∀ i, r i ∈ S))
    (t' := Fintype.piFinset (fun _ : Fin n => Finset.univ))
    (h := by
      intro S r
      simp only [Finset.mem_powerset, Fintype.mem_piFinset, Finset.mem_filter, Finset.mem_univ]
      tauto)]
  -- Step 3: Factor out tprod(f ∘ r) from the inner sum
  simp_rw [← Finset.sum_smul]
  -- Step 4: Evaluate inner coefficient using alternating_superset_sum
  have coeff_eq : ∀ r : Fin n → Fin n,
      (∑ S ∈ Finset.univ.powerset.filter (fun S => ∀ j, r j ∈ S),
        (-1 : k) ^ (n - S.card)) =
      if Finset.image r Finset.univ = Finset.univ then 1 else 0 := by
    intro r
    convert alternating_superset_sum k n (Finset.image r Finset.univ) using 2
    ext S; simp [Finset.subset_iff]
  simp_rw [coeff_eq]
  -- Step 5: Non-surjective terms vanish
  simp only [ite_smul, one_smul, zero_smul]
  rw [Finset.sum_ite, Finset.sum_const_zero, add_zero]
  -- Step 6: In the symmetric power, tprod(f ∘ σ) = tprod(f) for any permutation σ
  -- The sum is over surjective (= bijective for Fin n) functions
  -- Each gives tprod(f), and there are n! of them
  -- First, simplify tprod using symmetry: in the symmetric power, permuting args is identity
  have tprod_perm : ∀ (σ : Equiv.Perm (Fin n)),
      (⨂ₛ[k] (i : Fin n), f (σ i)) = SymmetricPower.tprod k f := by
    intro σ; exact SymmetricPower.tprod_equiv σ f
  -- Step 6a: Each term in the filtered sum equals tprod k f
  have all_eq : ∀ x ∈ (Fintype.piFinset fun _ : Fin n => Finset.univ).filter
        (fun x => Finset.image x Finset.univ = Finset.univ),
      (⨂ₛ[k] (i : Fin n), f (x i)) = SymmetricPower.tprod k f := by
    intro x hx
    simp only [Finset.mem_filter, Fintype.mem_piFinset] at hx
    have hxsurj : Function.Surjective x := by
      intro b
      have hb : b ∈ Finset.image x Finset.univ := by rw [hx.2]; exact Finset.mem_univ b
      exact let ⟨a, _, ha⟩ := Finset.mem_image.mp hb; ⟨a, ha⟩
    exact tprod_perm (Equiv.ofBijective x
      ((Finite.surjective_iff_bijective (α := Fin n)).mp hxsurj))
  rw [Finset.sum_congr rfl all_eq, Finset.sum_const, ← Nat.cast_smul_eq_nsmul k]
  congr 1
  -- Step 6b: Card of {r : Fin n → Fin n | image r univ = univ} = n!
  norm_cast
  -- Establish bijection with Perm (Fin n) via embedding
  let e : Equiv.Perm (Fin n) ↪ (Fin n → Fin n) :=
    ⟨fun σ => σ, fun σ₁ σ₂ h => Equiv.ext (congr_fun h)⟩
  have hmap : (Fintype.piFinset fun _ : Fin n => (Finset.univ : Finset (Fin n))).filter
        (fun x => Finset.image x Finset.univ = Finset.univ) =
      (Finset.univ : Finset (Equiv.Perm (Fin n))).map e := by
    ext r
    simp only [Finset.mem_filter, Fintype.mem_piFinset, Finset.mem_univ,
      Finset.mem_map]
    constructor
    · intro ⟨_, hr⟩
      have hsurj : Function.Surjective r := by
        intro b
        have : b ∈ Finset.image r Finset.univ := by rw [hr]; exact Finset.mem_univ b
        exact let ⟨a, _, ha⟩ := Finset.mem_image.mp this; ⟨a, ha⟩
      exact ⟨Equiv.ofBijective r
        ((Finite.surjective_iff_bijective (α := Fin n)).mp hsurj), trivial, rfl⟩
    · rintro ⟨σ, _, rfl⟩
      exact ⟨fun _ => trivial, Finset.image_univ_of_surjective σ.surjective⟩
  rw [hmap, Finset.card_map, Finset.card_univ, Fintype.card_perm, Fintype.card_fin]

/-- S^n U is spanned by n-fold tensor powers u^⊗n for u ∈ U, assuming characteristic zero.

Unlike the general spanning result `SymmetricPower.span_tprod_eq_top` (which says
all pure tensors `u₁ ⊗ u₂ ⊗ ... ⊗ uₙ` span), this states that the smaller set
of *diagonal* pure tensors `u ⊗ u ⊗ ... ⊗ u` already spans. This follows from
polarization: a symmetric multilinear form that vanishes on the diagonal determines
zero, so the diagonal tensors must span.

(Etingof Lemma 5.18.3, part i) -/
theorem span_diagonalTensors [CharZero k] :
    Submodule.span k (diagonalTensors k U n) = ⊤ := by
  rw [eq_top_iff, ← SymmetricPower.span_tprod_eq_top]
  apply Submodule.span_le.mpr
  rintro _ ⟨f, rfl⟩
  -- Need: tprod k f ∈ Submodule.span k (diagonalTensors k U n)
  have hfact : (n.factorial : k) ≠ 0 :=
    Nat.cast_ne_zero.mpr n.factorial_ne_zero
  rw [show SymmetricPower.tprod k f =
      (n.factorial : k)⁻¹ • ((n.factorial : k) • SymmetricPower.tprod k f) from
    (inv_smul_smul₀ hfact _).symm]
  rw [polarization_eq]
  apply Submodule.smul_mem
  apply Submodule.sum_mem
  intro S _
  apply Submodule.smul_mem
  exact Submodule.subset_span ⟨∑ i ∈ S, f i, rfl⟩

end Span

section Generated

variable (k : Type*) [Field k]
  (V : Type*) [AddCommGroup V] [Module k V] [Module.Finite k V]
  (n : ℕ)

/-- The subalgebra of End(V^⊗n) generated by diagonal elements Δ_n(b) for
b ∈ End(V), where Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1). -/
noncomputable def diagonalSubalgebra :
    Subalgebra k (Module.End k (⨂[k] (_ : Fin n), V)) :=
  Algebra.adjoin k (Set.range fun (b : Module.End k V) =>
    ∑ i : Fin n,
      PiTensorProduct.map (fun j => if j = i then b else LinearMap.id))

/-- The subalgebra of End(V^⊗n) generated by full diagonal operators
f ⊗ f ⊗ ... ⊗ f for f ∈ End(V). -/
noncomputable def fullDiagonalSubalgebra :
    Subalgebra k (Module.End k (⨂[k] (_ : Fin n), V)) :=
  Algebra.adjoin k (Set.range fun (f : Module.End k V) =>
    PiTensorProduct.map (fun _ => f))

/-- S^n A is generated by diagonal elements Δ_n(a) for a ∈ A.

The n-th symmetric power of an algebra A, viewed inside End(V^⊗n) via the
diagonal representation, is generated by the Lie algebra-type diagonal elements
Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1). In other words, the subalgebra generated
by these "additive" diagonal elements equals the subalgebra generated by the
"multiplicative" diagonal elements f ⊗ f ⊗ ... ⊗ f.

This follows from the fundamental theorem of symmetric functions: the power
sum symmetric polynomials generate the ring of symmetric polynomials.

## Proof sketch

Define position operators b_i = map(fun j => if j = i then b else id) ∈ End(V^⊗n).
These pairwise commute (by `PiTensorProduct.map_mul`, each position acts independently).

**⊇ direction (fullDiag ≤ diag):**
For f ∈ End(V), f^⊗n = ∏_i b_i (product of position operators, via `map_mul`).
Power sums p_m = Σ_i b_i^m = Δ_n(f^m) are generators of diag.
Newton's recurrence k · e_k = Σ_{j=1}^k (-1)^{j-1} e_{k-j} · p_j gives e_n ∈ Alg(p_1,...,p_n).
Since each p_m ∈ diag and diag is a subalgebra, e_n = ∏ b_i = f^⊗n ∈ diag.

Key infrastructure gaps:
- `MvPolynomial.aeval` requires `CommSemiring` target but End(V^⊗n) is noncommutative
- `Finset.prod` requires `CommMonoid` but End(V^⊗n) is only a `Monoid`
- Need Newton's identity for pairwise-commuting elements in a noncommutative ring

**⊆ direction (diag ≤ fullDiag):**
For b ∈ End(V) and c ∈ k, map(fun _ => c • id + b) ∈ fullDiag (generator with f = c·id + b).
By multilinearity (`PiTensorProduct.mapMultilinear`, `MultilinearMap.map_add_univ`):
  map(fun _ => c·id + b) = Σ_{k=0}^n c^{n-k} · (Σ_{|S|=k} map(fun j => if j ∈ S then b else id))
Evaluating at c = 0,1,...,n gives n+1 elements of fullDiag.
The Vandermonde matrix `[j^m]` is invertible (`Matrix.det_vandermonde_ne_zero_iff`, char 0).
So each coefficient — in particular e_1 = Δ_n(b) — is a k-linear combination ∈ fullDiag.

(Etingof Lemma 5.18.3, part ii) -/
-- Vandermonde coefficient extraction: evaluations of a module-valued polynomial
-- at 0, 1, ..., d in a submodule implies all coefficients are in the submodule.
private lemma polynomial_coeffs_in_submodule [CharZero k]
    {A : Type*} [AddCommGroup A] [Module k A]
    (M : Submodule k A)
    (d : ℕ) (a : Fin (d + 1) → A)
    (h_eval : ∀ j : Fin (d + 1),
      ∑ m : Fin (d + 1), ((j : ℕ) : k) ^ (m : ℕ) • a m ∈ M) :
    ∀ m : Fin (d + 1), a m ∈ M := by
  set v : Fin (d+1) → k := fun j => ((j : ℕ) : k)
  set V : Matrix (Fin (d+1)) (Fin (d+1)) k := Matrix.vandermonde v
  have hv_inj : Function.Injective v := by
    intro i j h; simp only [v] at h; exact Fin.ext (Nat.cast_injective h)
  have hV_unit : IsUnit V.det := by
    rw [isUnit_iff_ne_zero, Matrix.det_vandermonde_ne_zero_iff]; exact hv_inj
  have hWV : V⁻¹ * V = 1 := Matrix.nonsing_inv_mul V hV_unit
  intro m
  suffices h : a m = ∑ j : Fin (d+1), V⁻¹ m j •
      (∑ i : Fin (d+1), v j ^ (i : ℕ) • a i) by
    rw [h]; exact M.sum_mem fun j _ => M.smul_mem _ (h_eval j)
  simp_rw [Finset.smul_sum, smul_smul]
  rw [Finset.sum_comm]
  simp_rw [← Finset.sum_smul]
  have coeff_eq : ∀ i : Fin (d+1),
      (∑ j : Fin (d+1), V⁻¹ m j * v j ^ (i : ℕ)) = if m = i then 1 else 0 := by
    intro i
    change (∑ j, V⁻¹ m j * V j i) = _
    rw [show ∑ j, V⁻¹ m j * V j i = (V⁻¹ * V) m i from rfl, hWV, Matrix.one_apply]
  simp_rw [coeff_eq]; simp [ite_smul]

-- Helper: card of any subset of Fin n is < n+1
private lemma card_finset_fin_lt (S : Finset (Fin n)) : S.card < n + 1 := by
  have := S.card_le_univ; simp at this; omega

-- Regroup a sum over subsets by cardinality
open Finset in
set_option maxHeartbeats 800000 in
private lemma sum_regroup_by_card
    {M : Type*} [AddCommMonoid M] [Module k M]
    (f : Finset (Fin n) → M) (c : k) :
    ∑ S : Finset (Fin n), c ^ S.card • f S =
    ∑ m : Fin (n + 1), c ^ (m : ℕ) •
      ∑ S ∈ (univ : Finset (Finset (Fin n))).filter (fun S => S.card = m.val), f S := by
  let g : Finset (Fin n) → Fin (n + 1) := fun S =>
    ⟨S.card, card_finset_fin_lt n S⟩
  have hg : ∀ S ∈ (univ : Finset (Finset (Fin n))), g S ∈ (univ : Finset (Fin (n+1))) :=
    fun _ _ => mem_univ _
  rw [← sum_fiberwise_of_maps_to hg (fun S => c ^ S.card • f S)]
  congr 1; ext m
  simp_rw [smul_sum]
  apply sum_congr
  · ext S; simp only [mem_filter, mem_univ, true_and, g]
    constructor
    · intro h; have := congr_arg Fin.val h; simpa using this
    · intro h; exact Fin.ext h
  · intro S hS; simp only [mem_filter, mem_univ, true_and] at hS; simp [hS]

-- Subsets of size n-1 correspond to erasing single elements
set_option maxHeartbeats 800000 in
private lemma sum_card_pred_eq_sum_erase (hn : 0 < n)
    {M : Type*} [AddCommMonoid M]
    (f : Finset (Fin n) → M) :
    ∑ S ∈ (Finset.univ : Finset (Finset (Fin n))).filter
      (fun S => S.card = n - 1), f S =
    ∑ i : Fin n, f (Finset.univ.erase i) := by
  symm
  apply Finset.sum_bij (fun i _ => Finset.univ.erase i)
  · intro i _
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    rw [Finset.card_erase_of_mem (Finset.mem_univ i), Finset.card_univ, Fintype.card_fin]
  · intro i _ j _ h
    by_contra hij
    have : i ∈ Finset.univ.erase j :=
      Finset.mem_erase.mpr ⟨hij, Finset.mem_univ _⟩
    rw [← h] at this
    exact absurd rfl (Finset.mem_erase.mp this).1
  · intro S hS
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hS
    have hcard : (Finset.univ \ S).card = 1 := by
      rw [Finset.card_sdiff_of_subset (Finset.subset_univ S), Finset.card_univ,
        Fintype.card_fin]; omega
    obtain ⟨i, hi⟩ := Finset.card_eq_one.mp hcard
    refine ⟨i, Finset.mem_univ _, ?_⟩
    ext x; constructor
    · intro hxE
      have hne := (Finset.mem_erase.mp hxE).1
      by_contra hxS
      have : x ∈ Finset.univ \ S := Finset.mem_sdiff.mpr ⟨Finset.mem_univ _, hxS⟩
      rw [hi] at this
      exact hne (Finset.mem_singleton.mp this)
    · intro hxS
      refine Finset.mem_erase.mpr ⟨?_, Finset.mem_univ _⟩
      intro hxi
      have : x ∈ Finset.univ \ S := hi ▸ Finset.mem_singleton.mpr hxi
      exact (Finset.mem_sdiff.mp this).2 hxS
  · intro i _; rfl

-- Piecewise on complement of singleton = if-then-else
omit [Module.Finite k V] in
private lemma piecewise_erase_eq {α : Type*} [DecidableEq α] [Fintype α]
    {β : Type*} (i : α) (f g : β) :
    (Finset.univ.erase i).piecewise (fun _ => f) (fun _ => g) =
    fun j => if j = i then g else f := by
  ext x
  simp only [Finset.piecewise, Finset.mem_erase, Finset.mem_univ, and_true]
  -- Goal: (if x ≠ i then f else g) = (if x = i then g else f)
  by_cases hx : x = i <;> simp [hx]

-- ⊆ direction: diag ≤ fullDiag via multilinear expansion + Vandermonde
set_option maxHeartbeats 3200000 in -- multilinear expansion over 2^n subsets + Vandermonde
omit [Module.Finite k V] in
private lemma diag_le_fullDiag [CharZero k] :
    diagonalSubalgebra k V n ≤ fullDiagonalSubalgebra k V n := by
  apply Algebra.adjoin_le
  rintro _ ⟨b, rfl⟩
  -- Need: Δ_n(b) = ∑ i, map(fun j => if j = i then b else id) ∈ fullDiag
  -- Handle n = 0: empty sum is 0, trivially in any subalgebra
  by_cases hn : n = 0
  · subst hn; simp [Finset.sum_empty]
  · push_neg at hn; have hn' : 0 < n := Nat.pos_of_ne_zero hn
    -- Use the multilinear map
    let mm := PiTensorProduct.mapMultilinear k (fun _ : Fin n => V) (fun _ => V)
    -- Define coefficients grouped by subset cardinality
    set a : Fin (n + 1) → Module.End k (⨂[k] (_ : Fin n), V) :=
      fun m => ∑ S ∈ (Finset.univ : Finset (Finset (Fin n))).filter
        (fun S => S.card = m.val),
        mm (S.piecewise (fun _ => LinearMap.id) (fun _ => b))
    -- Step 1: evaluations at integers equal map applied to (c•id + b)
    have h_eval : ∀ j : Fin (n + 1),
        ∑ m : Fin (n + 1), ((j : ℕ) : k) ^ (m : ℕ) • a m =
          mm (fun _ => ((j : ℕ) : k) • LinearMap.id + b) := by
      intro j
      simp only [a]
      rw [← sum_regroup_by_card]
      symm
      have key : (fun (_ : Fin n) => ((j : ℕ) : k) • LinearMap.id + b) =
          (fun _ => ((j : ℕ) : k) • LinearMap.id) + (fun _ => b) := by
        ext; simp [Pi.add_apply]
      rw [key, mm.map_add_univ]
      apply Finset.sum_congr rfl; intro S _
      set base := S.piecewise (fun _ : Fin n => LinearMap.id) (fun _ => b)
      have h2 := mm.map_piecewise_smul (fun _ => ((j : ℕ) : k)) base S
      simp only [Finset.prod_const] at h2
      rw [← h2]
      congr 1; funext i
      simp only [Finset.piecewise, base]
      split_ifs with h <;> simp
    -- Step 2: each evaluation ∈ fullDiag
    have h_mem : ∀ j : Fin (n + 1),
        ∑ m : Fin (n + 1), ((j : ℕ) : k) ^ (m : ℕ) • a m ∈
          (fullDiagonalSubalgebra k V n).toSubmodule := by
      intro j; rw [h_eval]
      exact Algebra.subset_adjoin ⟨_, rfl⟩
    -- Step 3: all coefficients ∈ fullDiag by Vandermonde
    have h_all := polynomial_coeffs_in_submodule k
      (fullDiagonalSubalgebra k V n).toSubmodule n a h_mem
    -- Step 4: a(n-1) = Δ_n(b)
    have h_target := h_all ⟨n - 1, by omega⟩
    simp only [a] at h_target
    rw [sum_card_pred_eq_sum_erase n hn'] at h_target
    -- Now h_target : ∑ i, mm((univ.erase i).piecewise id b) ∈ fullDiag.toSubmodule
    -- Identify each term: mm((univ.erase i).piecewise id b) = map(fun j => if j=i then b else id)
    simp_rw [show ∀ i : Fin n, mm ((Finset.univ.erase i).piecewise
        (fun _ => LinearMap.id) (fun _ => b)) =
        PiTensorProduct.map (fun j => if j = i then b else LinearMap.id) from
      fun i => by
        change mm _ = mm _; congr 1
        rw [piecewise_erase_eq]] at h_target
    exact h_target

-- ⊇ direction: fullDiag ≤ diag via Newton's identity for commuting position operators
-- Position operator B_i(f) acts as f on tensor position i, identity elsewhere.
-- These pairwise commute, and their product Π_i B_i = f^⊗n (full diagonal generator).
-- Newton's identity expresses Π_i B_i as a polynomial in power sums
-- p_m = Σ_i B_i^m = Δ_n(f^m), which are generators of diag.
omit [Module.Finite k V] in
private lemma fullDiag_le_diag [CharZero k] :
    fullDiagonalSubalgebra k V n ≤ diagonalSubalgebra k V n := by
  apply Algebra.adjoin_le
  rintro _ ⟨f, rfl⟩
  -- Need: PiTensorProduct.map (fun _ => f) ∈ diagonalSubalgebra
  -- Define position operators B_i(f) = map(fun j => if j = i then f else id)
  set B : Fin n → Module.End k (⨂[k] (_ : Fin n), V) :=
    fun i => PiTensorProduct.map (fun j => if j = i then f else LinearMap.id)
  -- B_i commute (they act on independent positions)
  have hcomm : ∀ i j, Commute (B i) (B j) := by
    intro i j
    change B i * B j = B j * B i
    simp only [B, ← PiTensorProduct.map_mul]
    congr 1; ext x
    dsimp only [Pi.mul_apply]
    by_cases hi : x = i <;> by_cases hj : x = j <;> simp_all
  -- B_i^m = map(fun j => if j = i then f^m else id) (position operator of f^m)
  have hpow : ∀ i m, B i ^ m = PiTensorProduct.map
      (fun j => if j = i then f ^ m else LinearMap.id) := by
    intro i m; simp only [B, ← PiTensorProduct.map_pow]
    congr 1; ext x; by_cases h : x = i <;> simp [h]
  -- Power sum p_m = Σ_i B_i^m = Δ_n(f^m) ∈ diag
  have hpsum : ∀ m, 0 < m → ∑ i, B i ^ m ∈ (diagonalSubalgebra k V n : Set _) := by
    intro m _; simp_rw [hpow]; exact Algebra.subset_adjoin ⟨f ^ m, rfl⟩
  -- Elementary symmetric function: e_m = Σ_{|S|=m} noncommProd_S(B)
  set e : ℕ → Module.End k (⨂[k] (_ : Fin n), V) := fun m =>
    ∑ S ∈ (Finset.univ : Finset (Fin n)).powersetCard m,
      S.noncommProd B (fun i _ j _ _ => hcomm i j)
  -- e_n = map(fun _ => f) (the full diagonal generator)
  suffices heq : e n = PiTensorProduct.map (fun _ => f) by
    change PiTensorProduct.map (fun _ => f) ∈ _
    rw [← heq]
    -- By strong induction, show e m ∈ diag for all m
    suffices ∀ m, e m ∈ diagonalSubalgebra k V n from this n
    intro m
    induction m using Nat.strongRecOn with | ind m ih => ?_
    by_cases hm : m = 0
    · subst hm; simp [e, Finset.powersetCard_zero]
    · -- For m ≥ 1: use Newton's identity
        -- m • e_m = Σ_{j < m} (-1)^j • (e_j * p_{m-j})
        have hm' : 0 < m := Nat.pos_of_ne_zero hm
        have hcast : (m : k) ≠ 0 := Nat.cast_ne_zero.mpr hm
        -- Newton's identity via commutative subalgebra transfer
        have newton : (m : k) • e m =
            (-1 : k) ^ (m + 1) • ∑ j ∈ Finset.range m,
              ((-1 : k) ^ j) • (e j * ∑ i : Fin n, B i ^ (m - j)) := by
          -- Build a commutative subalgebra from pairwise-commuting generators
          set A := Algebra.adjoin k (Set.range B)
          have hBA : ∀ i, B i ∈ A := fun i => Algebra.subset_adjoin ⟨i, rfl⟩
          -- All elements of A commute (generators commute, closure properties)
          have hcommA : ∀ (a b : A), a * b = b * a := by
            intro a b; apply Subtype.ext; show a.val * b.val = b.val * a.val
            exact Algebra.adjoin_induction₂
              (fun _ _ ⟨i, hi⟩ ⟨j, hj⟩ => hi ▸ hj ▸ hcomm i j)
              (fun r₁ r₂ => by rw [← map_mul, mul_comm, map_mul])
              (fun r _ _ => Algebra.commutes r _)
              (fun r _ _ => (Algebra.commutes r _).symm)
              (fun _ _ _ _ _ _ h₁ h₂ => by rw [add_mul, mul_add, h₁, h₂])
              (fun _ _ _ _ _ _ h₁ h₂ => by rw [mul_add, add_mul, h₁, h₂])
              (fun _ _ _ _ _ _ h₁ h₂ => by rw [mul_assoc, h₂, ← mul_assoc, h₁, mul_assoc])
              (fun _ _ _ _ _ _ h₁ h₂ => by rw [← mul_assoc, h₁, mul_assoc, h₂, ← mul_assoc])
              a.property b.property
          -- CommRing instance on A
          letI : CommRing A := { show Ring A from inferInstance with mul_comm := hcommA }
          -- Lift B into A
          set B' : Fin n → A := fun i => ⟨B i, hBA i⟩
          -- Evaluation algebra homomorphism
          set ψ : MvPolynomial (Fin n) k →ₐ[k] A := MvPolynomial.aeval B' with hψ_def
          -- Product in A coerces to noncommProd in End
          have prod_val : ∀ S : Finset (Fin n),
              (∏ i ∈ S, B' i : A).val =
                S.noncommProd B (fun i _ j _ _ => hcomm i j) := by
            intro S
            induction S using Finset.cons_induction_on with
            | empty => simp [Finset.noncommProd_empty]
            | cons a s ha ih =>
              rw [Finset.prod_cons, Finset.noncommProd_cons]
              show (B' a * ∏ i ∈ s, B' i).val = B a * s.noncommProd B _
              simp only [Subalgebra.coe_mul]; rw [ih]
          -- ψ maps esymm to e
          have esymm_val : ∀ j,
              (ψ (MvPolynomial.esymm (Fin n) k j) : Module.End k _) = e j := by
            intro j
            simp only [MvPolynomial.esymm, map_sum, map_prod, MvPolynomial.aeval_X, hψ_def, e]
            rw [AddSubmonoidClass.coe_finset_sum]
            exact Finset.sum_congr rfl (fun T _ => prod_val T)
          -- ψ maps psum to power sum
          have psum_val : ∀ d,
              (ψ (MvPolynomial.psum (Fin n) k d) : Module.End k _) =
                ∑ i : Fin n, B i ^ d := by
            intro d
            simp only [MvPolynomial.psum, map_sum, map_pow, MvPolynomial.aeval_X, hψ_def]
            simp only [AddSubmonoidClass.coe_finset_sum, SubmonoidClass.coe_pow, B']
          -- Composite evaluation: MvPolynomial → A → End
          set Φ : MvPolynomial (Fin n) k →ₐ[k] Module.End k (⨂[k] (_ : Fin n), V) :=
            A.val.comp ψ
          have Φ_esymm : ∀ j, Φ (MvPolynomial.esymm (Fin n) k j) = e j := esymm_val
          have Φ_psum : ∀ d, Φ (MvPolynomial.psum (Fin n) k d) = ∑ i : Fin n, B i ^ d :=
            psum_val
          -- Apply Φ to Mathlib's Newton identity
          have h := congr_arg Φ (MvPolynomial.mul_esymm_eq_sum (Fin n) k m)
          simp only [map_mul, map_pow, map_neg, map_one, map_sum,
            Φ_esymm, Φ_psum] at h
          rw [map_natCast Φ m] at h
          -- h : ↑m * e m = (-1)^(m+1) * ∑ antidiag, (-1)^x.1 * e x.1 * ∑ i, B i ^ x.2
          -- Convert antidiagonal sum to range sum in h
          rw [show (Finset.antidiagonal m).filter (fun x => x.1 < m) =
              (Finset.range m).map ⟨fun j => (j, m - j), fun a b h => by
                simp [Prod.ext_iff] at h; exact h.1⟩ from by
            ext ⟨a, b⟩; simp [Finset.mem_antidiagonal, Finset.mem_range]; omega,
            Finset.sum_map] at h
          simp only [Function.Embedding.coeFn_mk] at h
          -- h : ↑m * e m = (-1)^(m+1) * ∑ j ∈ range m, (-1)^j * e j * ∑ i, B i ^ (m-j)
          -- Convert goal from • to *, then use h
          rw [Nat.cast_smul_eq_nsmul k m (e m), nsmul_eq_mul, h]
          -- Goal: (-1)^(m+1) * ∑ ... = (-1:k)^(m+1) • ∑ j, (-1:k)^j • (e j * ∑ ...)
          -- Convert (-1 : End)^p to algebraMap and * to •
          have neg_pow_smul : ∀ (p : ℕ)
              (x : Module.End k (⨂[k] (_ : Fin n), V)),
              (-1 : Module.End k (⨂[k] (_ : Fin n), V)) ^ p * x = (-1 : k) ^ p • x := by
            intro p x
            have : (-1 : Module.End k (⨂[k] (_ : Fin n), V)) =
                algebraMap k _ (-1 : k) := by
              simp [map_neg, map_one]
            rw [this, ← map_pow, Algebra.smul_def]
          rw [neg_pow_smul]; congr 1
          apply Finset.sum_congr rfl; intro j _
          rw [mul_assoc, neg_pow_smul]
        rw [show e m = (m : k)⁻¹ • ((m : k) • e m) from (inv_smul_smul₀ hcast _).symm,
          newton]
        apply Subalgebra.smul_mem
        apply Subalgebra.smul_mem
        apply Subalgebra.sum_mem
        intro j hj
        have hjm : j < m := Finset.mem_range.mp hj
        apply Subalgebra.smul_mem
        apply Subalgebra.mul_mem
        · exact ih j hjm
        · exact hpsum (m - j) (Nat.sub_pos_of_lt hjm)
  -- Proof that e_n = map(fun _ => f):
  -- e_n has exactly one summand (S = univ) since powersetCard n univ = {univ}
  simp only [e]
  have hcard : (Finset.univ : Finset (Fin n)).card = n :=
    Finset.card_univ.trans (Fintype.card_fin n)
  have huniv : (Finset.univ : Finset (Fin n)).powersetCard n = {Finset.univ} := by
    have := Finset.powersetCard_self (Finset.univ : Finset (Fin n))
    rwa [hcard] at this
  rw [huniv, Finset.sum_singleton]
  -- noncommProd of B over univ = map(fun _ => f)
  -- Strategy: pull PiTensorProduct.map out of noncommProd, reduce to Pi-level identity
  -- First show via map_noncommProd that mapMonoidHom commutes with noncommProd
  set piF : Fin n → (Fin n → Module.End k V) :=
    fun i j => if j = i then f else LinearMap.id with hpiF_def
  have hpiFcomm : ∀ i ∈ (Finset.univ : Finset (Fin n)),
      ∀ j ∈ (Finset.univ : Finset (Fin n)), i ≠ j →
      Commute (piF i) (piF j) := by
    intro i _ j _ _
    ext x; simp only [Pi.mul_apply, piF]
    by_cases hi : x = i <;> by_cases hj : x = j <;> simp_all
  -- The Pi-level product: for each position j, ∏_i piF(i)(j) = f
  have piF_prod : Finset.univ.noncommProd piF hpiFcomm = fun _ => f := by
    funext j
    change (Pi.evalMonoidHom (fun _ : Fin n => Module.End k V) j)
      (Finset.univ.noncommProd piF hpiFcomm) = f
    rw [Finset.map_noncommProd _ _ _ (Pi.evalMonoidHom (fun _ : Fin n => Module.End k V) j)]
    change Finset.univ.noncommProd (fun i => piF i j) _ = f
    simp only [piF]
    conv_lhs => rw [← Finset.mul_noncommProd_erase _ (Finset.mem_univ j)]
    simp only [ite_true]
    suffices h : (Finset.univ.erase j).noncommProd
        (fun i => if j = i then f else LinearMap.id) _ = 1 by
      rw [h, mul_one]
    rw [Finset.noncommProd_eq_pow_card _ _ _ (1 : Module.End k V)
      (fun i hi => by simp only [Ne.symm (Finset.mem_erase.mp hi).1, ite_false]; rfl), one_pow]
  -- Now connect: B i = mapMonoidHom (piF i), so noncommProd B = mapMonoidHom (noncommProd piF)
  have key := Finset.map_noncommProd Finset.univ piF hpiFcomm PiTensorProduct.mapMonoidHom
  -- key : mapMonoidHom (noncommProd piF _) = noncommProd (fun i => mapMonoidHom (piF i)) _
  rw [piF_prod] at key
  -- key : map (fun _ => f) = noncommProd (fun i => map (piF i)) _
  -- Goal: noncommProd B _ = map (fun _ => f)
  -- B i = mapMonoidHom (piF i), so noncommProd B = noncommProd (mapMonoidHom ∘ piF)
  have hBeq : ∀ i ∈ Finset.univ, B i = PiTensorProduct.mapMonoidHom (piF i) := by
    intro i _; simp [B, piF]
  rw [Finset.noncommProd_congr rfl hBeq, ← key]; rfl

omit [Module.Finite k V] in
theorem diagonalSubalgebra_eq_fullDiagonal [CharZero k] :
    diagonalSubalgebra k V n = fullDiagonalSubalgebra k V n :=
  le_antisymm (diag_le_fullDiag k V n) (fullDiag_le_diag k V n)

end Generated

end Etingof.Lemma5_18_3
