import Mathlib

/-!
# Lemma 5.18.3: Symmetric Power Generation

Two key generation results:

(i) S^n U (the n-th symmetric power) is spanned by elements of the form
    u ⊗ u ⊗ ... ⊗ u (n times) for u ∈ U. This follows from the fact that
    S^n U is an irreducible GL(U)-module.

(ii) S^n A (for an algebra A) is generated as an algebra by elements Δ_n(a)
     for a ∈ A, where Δ_n(a) = a⊗1⊗...⊗1 + 1⊗a⊗...⊗1 + ... + 1⊗...⊗1⊗a.
     This follows from the fundamental theorem of symmetric functions.

## Mathlib correspondence

Mathlib has `SymmetricPower` and basic symmetric algebra theory. The specific
generation results may need custom proofs.
-/

/-- S^n U is spanned by n-fold tensor powers u^⊗n for u ∈ U.
(Etingof Lemma 5.18.3, part i) -/
theorem Etingof.Lemma5_18_3_span
    (k : Type*) [Field k]
    (U : Type*) [AddCommGroup U] [Module k U] [Module.Finite k U]
    (n : ℕ) :
    -- S^n U = span { u⊗...⊗u : u ∈ U }
    (sorry : Prop) := by
  sorry

/-- S^n A is generated by diagonal elements Δ_n(a) for a ∈ A.
(Etingof Lemma 5.18.3, part ii) -/
theorem Etingof.Lemma5_18_3_generated
    (k : Type*) [Field k]
    (A : Type*) [Ring A] [Algebra k A] [Module.Finite k A]
    (n : ℕ) :
    -- S^n A is generated by { Δ_n(a) : a ∈ A }
    (sorry : Prop) := by
  sorry
