import Mathlib

/-!
# Lemma 5.18.3: Symmetric Power Generation

Two key generation results:

(i) S^n U (the n-th symmetric power) is spanned by elements of the form
    u ⊗ u ⊗ ... ⊗ u (n times) for u ∈ U. This follows from the fact that
    S^n U is an irreducible GL(U)-module (equivalently, by polarization).

(ii) S^n A (for an algebra A) is generated as an algebra by elements Δ_n(a)
     for a ∈ A, where Δ_n(a) = a⊗1⊗...⊗1 + 1⊗a⊗...⊗1 + ... + 1⊗...⊗1⊗a.
     This follows from the fundamental theorem of symmetric functions.

## Mathlib correspondence

- `SymmetricPower` for S^n U (quotient of `PiTensorProduct` by permutations)
- `SymmetricPower.tprod` for the canonical multilinear map to the symmetric power
- `Submodule.span` for module generation
- The algebra structure on S^n A is not yet in Mathlib (listed as TODO).
  Part (ii) is stated in terms of the subalgebra generated by diagonal operators
  in End(V^⊗n), which captures the same content in the representation-theoretic
  context where this lemma is applied.
-/

open scoped TensorProduct

namespace Etingof.Lemma5_18_3

section Span

variable (k : Type) [Field k]
  (U : Type*) [AddCommGroup U] [Module k U] [Module.Finite k U]
  (n : ℕ)

/-- The set of n-fold diagonal symmetric tensors u^⊗n for u ∈ U.
These are elements of S^n U of the form u ⊗ u ⊗ ... ⊗ u (n times). -/
def diagonalTensors : Set (Sym[k]^n U) :=
  Set.range (fun u : U => SymmetricPower.tprod k (fun (_ : Fin n) => u))

/-- S^n U is spanned by n-fold tensor powers u^⊗n for u ∈ U.

Unlike the general spanning result `SymmetricPower.span_tprod_eq_top` (which says
all pure tensors `u₁ ⊗ u₂ ⊗ ... ⊗ uₙ` span), this states that the smaller set
of *diagonal* pure tensors `u ⊗ u ⊗ ... ⊗ u` already spans. This follows from
polarization: a symmetric multilinear form that vanishes on the diagonal determines
zero, so the diagonal tensors must span.

(Etingof Lemma 5.18.3, part i) -/
theorem span_diagonalTensors :
    Submodule.span k (diagonalTensors k U n) = ⊤ := by
  sorry

end Span

section Generated

variable (k : Type*) [Field k]
  (V : Type*) [AddCommGroup V] [Module k V] [Module.Finite k V]
  (n : ℕ)

/-- The subalgebra of End(V^⊗n) generated by diagonal elements Δ_n(b) for
b ∈ End(V), where Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1). -/
noncomputable def diagonalSubalgebra :
    Subalgebra k (Module.End k (⨂[k] (_ : Fin n), V)) :=
  Algebra.adjoin k (Set.range fun (b : Module.End k V) =>
    ∑ i : Fin n,
      PiTensorProduct.map (fun j => if j = i then b else LinearMap.id))

/-- The subalgebra of End(V^⊗n) generated by full diagonal operators
f ⊗ f ⊗ ... ⊗ f for f ∈ End(V). -/
noncomputable def fullDiagonalSubalgebra :
    Subalgebra k (Module.End k (⨂[k] (_ : Fin n), V)) :=
  Algebra.adjoin k (Set.range fun (f : Module.End k V) =>
    PiTensorProduct.map (fun _ => f))

/-- S^n A is generated by diagonal elements Δ_n(a) for a ∈ A.

The n-th symmetric power of an algebra A, viewed inside End(V^⊗n) via the
diagonal representation, is generated by the Lie algebra-type diagonal elements
Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1). In other words, the subalgebra generated
by these "additive" diagonal elements equals the subalgebra generated by the
"multiplicative" diagonal elements f ⊗ f ⊗ ... ⊗ f.

This follows from the fundamental theorem of symmetric functions: the power
sum symmetric polynomials generate the ring of symmetric polynomials.

(Etingof Lemma 5.18.3, part ii) -/
theorem diagonalSubalgebra_eq_fullDiagonal :
    diagonalSubalgebra k V n = fullDiagonalSubalgebra k V n := by
  sorry

end Generated

end Etingof.Lemma5_18_3
