import EtingofRepresentationTheory.Chapter5.Theorem5_18_4

/-!
# Proposition 5.19.1: Image of GL(V) spans the centralizer algebra

The image of GL(V) in End(V⊗ⁿ) spans B (the centralizer algebra of the
Sₙ-action). This follows from the fact that the span of g⊗ⁿ for g ∈ GL(V)
equals the span of b⊗ⁿ for all b ∈ End(V), using a polynomial argument.

## Mathlib correspondence

Requires tensor power and Schur-Weyl duality infrastructure not yet in Mathlib.
-/

open Etingof

/-- The image of GL(V) in End(V⊗ⁿ) spans the centralizer algebra B of the
Sₙ-action on V⊗ⁿ. Specifically, the linear span of {g⊗ⁿ | g ∈ GL(V)}
(where g⊗ⁿ acts as g on each tensor factor) equals the full diagonal
action subalgebra generated by all of End(V), as a submodule.

This is a consequence of the polynomial density argument: if a polynomial
p(t) = det(f + t·id) vanishes for all t, then f is not invertible, but
the set of invertible operators is Zariski-dense in End(V), so the span
of {g⊗ⁿ | g ∈ GL(V)} equals the span of {f⊗ⁿ | f ∈ End(V)}.
(Etingof Proposition 5.19.1) -/
theorem Etingof.Proposition5_19_1
    {k : Type*} [Field k] [IsAlgClosed k]
    {V : Type*} [AddCommGroup V] [Module k V] [Module.Finite k V]
    (n : ℕ) :
    -- The linear span of {g⊗ⁿ | g ∈ GL(V)} equals the diagonal action image
    Submodule.span k (Set.range fun (g : V ≃ₗ[k] V) =>
      PiTensorProduct.map (fun (_ : Fin n) => g.toLinearMap)) =
    (diagonalActionImage k V n).toSubmodule := by
  sorry
