import Mathlib
import EtingofRepresentationTheory.Chapter5.Proposition5_21_1
import EtingofRepresentationTheory.Chapter5.Definition5_12_1
import EtingofRepresentationTheory.Chapter5.Theorem5_18_4

/-!
# Theorem 5.22.1: Weyl Character Formula for GL(V)

## Construction

The Schur module `L_λ` is the image of the Young symmetrizer `c_λ` acting
on the tensor power `(k^N)^{⊗n}` where `n = ∑ λᵢ`. The GL_N(k)-action
on this image comes from the diagonal action `g ↦ g⊗g⊗…⊗g`, which
commutes with the symmetric group action (hence with `c_λ`), so the image
is GL_N-stable.
-/

open MvPolynomial Finset CategoryTheory

noncomputable section

namespace Etingof

/-! ### Weight to partition conversion -/

/-- Convert a weight vector `lam : Fin N → ℕ` to a partition of `∑ i, lam i`. -/
def weightToPartition (N : ℕ) (lam : Fin N → ℕ) :
    Nat.Partition (∑ i, lam i) where
  parts := (Finset.univ.val.map lam).filter (0 < ·)
  parts_pos hi := (Multiset.mem_filter.mp hi).2
  parts_sum := by
    have h_filt : ∀ (s : Multiset ℕ), (s.filter (0 < ·)).sum = s.sum := by
      intro s
      induction s using Multiset.induction with
      | empty => simp
      | cons a s ih =>
        simp only [Multiset.filter_cons]
        split
        · simp [Multiset.sum_cons, ih]
        · rename_i h; push_neg at h; simp [Nat.le_zero.mp h, ih]
    rw [h_filt]
    simp [Finset.sum]

/-! ### Young symmetrizer over a general field -/

/-- The Young symmetrizer `c_λ = a_λ · b_λ` in `k[S_n]`, over a general field `k`. -/
def YoungSymmetrizerK (k : Type*) [CommRing k] (n : ℕ) (la : Nat.Partition n) :
    MonoidAlgebra k (Equiv.Perm (Fin n)) :=
  haveI : DecidablePred (· ∈ RowSubgroup n la) := Classical.decPred _
  haveI : DecidablePred (· ∈ ColumnSubgroup n la) := Classical.decPred _
  (∑ g : (RowSubgroup n la), MonoidAlgebra.of k _ g.val) *
  (∑ g : (ColumnSubgroup n la),
    ((↑(Equiv.Perm.sign g.val) : ℤ) : k) • MonoidAlgebra.of k _ g.val)

/-! ### Young symmetrizer endomorphism on tensor power -/

/-- The Young symmetrizer `c_λ` lifted to an endomorphism of `V^{⊗n}`. -/
def youngSymEndomorphism (k : Type*) [Field k] (N : ℕ) (lam : Fin N → ℕ) :
    Module.End k (TensorPower k (Fin N → k) (∑ i, lam i)) :=
  symGroupAlgHom k (Fin N → k) (∑ i, lam i)
    (YoungSymmetrizerK k (∑ i, lam i) (weightToPartition N lam))

/-! ### GL_N representation on tensor power -/

/-- The diagonal action of `GL_N(k)` on `V^{⊗n}`: `g` acts as `g ⊗ g ⊗ … ⊗ g`.
The representation map sends `g ∈ GL_N(k)` to the linear endomorphism
`PiTensorProduct.map (fun _ => g.val.mulVecLin)`. -/
def glTensorRep (k : Type*) [Field k] (N n : ℕ) :
    Representation k (Matrix.GeneralLinearGroup (Fin N) k)
      (TensorPower k (Fin N → k) n) where
  toFun g := PiTensorProduct.map (fun _ : Fin n => Matrix.mulVecLin (R := k) g.val)
  map_one' := by
    classical
    change PiTensorProduct.map (fun _ : Fin n => Matrix.mulVecLin (R := k) (1 : Matrix _ _ k)) =
      LinearMap.id
    have : (fun _ : Fin n => Matrix.mulVecLin (R := k) (1 : Matrix _ _ k)) =
        (fun _ : Fin n => (LinearMap.id : (Fin N → k) →ₗ[k] (Fin N → k))) :=
      funext fun _ => Matrix.mulVecLin_one
    rw [this, PiTensorProduct.map_id]
  map_mul' g₁ g₂ := by
    classical
    change PiTensorProduct.map (fun _ : Fin n => Matrix.mulVecLin (R := k) (g₁.val * g₂.val)) =
      (PiTensorProduct.map (fun _ : Fin n => Matrix.mulVecLin g₁.val)) ∘ₗ
      (PiTensorProduct.map (fun _ : Fin n => Matrix.mulVecLin g₂.val))
    have : (fun _ : Fin n => Matrix.mulVecLin (R := k) (g₁.val * g₂.val)) =
        (fun _ : Fin n => (Matrix.mulVecLin g₁.val).comp (Matrix.mulVecLin g₂.val)) :=
      funext fun _ => Matrix.mulVecLin_mul g₁.val g₂.val
    rw [this, PiTensorProduct.map_comp]

/-! ### GL action commutes with Young symmetrizer -/

/-- The GL_N diagonal action commutes with the Young symmetrizer endomorphism.
The GL action commutes with each permutation operator σ ∈ S_n by
`symGroupAction_comm_diagonalAction`, hence with any element of k[S_n],
hence with the Young symmetrizer. -/
theorem glTensor_comm_youngSym (k : Type*) [Field k] (N : ℕ) (lam : Fin N → ℕ)
    (g : Matrix.GeneralLinearGroup (Fin N) k) :
    glTensorRep k N (∑ i, lam i) g ∘ₗ youngSymEndomorphism k N lam =
    youngSymEndomorphism k N lam ∘ₗ glTensorRep k N (∑ i, lam i) g := by
  set n := ∑ i, lam i
  set V := Fin N → k
  set f : V →ₗ[k] V := Matrix.mulVecLin g.val
  -- The Young symmetrizer endomorphism is in symGroupImage (range of symGroupAlgHom)
  have h_sym : (youngSymEndomorphism k N lam : Module.End k (TensorPower k V n)) ∈
      (symGroupImage k V n : Set (Module.End k (TensorPower k V n))) := by
    rw [← symGroupAlgHom_range k V n]
    exact ⟨_, rfl⟩
  -- The GL tensor action is in diagonalActionImage (generated by PiTensorProduct.map f)
  have h_diag : (glTensorRep k N n g : Module.End k (TensorPower k V n)) ∈
      (diagonalActionImage k V n : Set (Module.End k (TensorPower k V n))) := by
    apply Algebra.subset_adjoin
    exact ⟨f, rfl⟩
  -- By diagonalActionImage_le_centralizer_symGroupImage, diagonal elements
  -- commute with all symmetric group elements
  have hcent := diagonalActionImage_le_centralizer_symGroupImage k V n h_diag
  rw [Subalgebra.mem_centralizer_iff] at hcent
  -- Get commutativity: young * g_tensor = g_tensor * young
  exact (hcent _ h_sym).symm

/-- The image of the Young symmetrizer is GL_N-stable. -/
theorem glTensorRep_mem_range (k : Type*) [Field k] (N : ℕ) (lam : Fin N → ℕ)
    (g : Matrix.GeneralLinearGroup (Fin N) k) (v : TensorPower k (Fin N → k) (∑ i, lam i))
    (hv : v ∈ LinearMap.range (youngSymEndomorphism k N lam)) :
    (glTensorRep k N (∑ i, lam i) g) v ∈ LinearMap.range (youngSymEndomorphism k N lam) := by
  obtain ⟨w, rfl⟩ := hv
  exact ⟨(glTensorRep k N (∑ i, lam i) g) w,
    (LinearMap.ext_iff.mp (glTensor_comm_youngSym k N lam g) w).symm⟩

/-! ### Schur module construction -/

/-- The Schur module as a submodule of `V^{⊗n}`: the image of the Young symmetrizer. -/
def SchurModuleSubmodule (k : Type*) [Field k] (N : ℕ) (lam : Fin N → ℕ) :
    Submodule k (TensorPower k (Fin N → k) (∑ i, lam i)) :=
  LinearMap.range (youngSymEndomorphism k N lam)

/-- The GL_N(k) representation restricted to the Schur module submodule.
The representation sends `g` to the restriction of `g^{⊗n}` to the image
of the Young symmetrizer, which is stable because GL_N commutes with S_n. -/
def schurModuleRep (k : Type*) [Field k] (N : ℕ) (lam : Fin N → ℕ) :
    Representation k (Matrix.GeneralLinearGroup (Fin N) k)
      (SchurModuleSubmodule k N lam) where
  toFun g := (glTensorRep k N (∑ i, lam i) g).restrict
    (p := SchurModuleSubmodule k N lam) (q := SchurModuleSubmodule k N lam)
    (fun v hv => glTensorRep_mem_range k N lam g v hv)
  map_one' := by
    ext ⟨v, hv⟩
    simp only [LinearMap.restrict_coe_apply]
    exact LinearMap.ext_iff.mp (map_one (glTensorRep k N _)) v
  map_mul' g₁ g₂ := by
    ext ⟨v, hv⟩
    -- After ext, both sides coerce to elements of TensorPower via restrict_coe_apply
    have h_mul := LinearMap.ext_iff.mp (map_mul (glTensorRep k N (∑ i, lam i)) g₁ g₂) v
    -- h_mul : (glTensorRep (g₁ * g₂)) v = (glTensorRep g₁ * glTensorRep g₂) v
    --       = (glTensorRep g₁) ((glTensorRep g₂) v)
    -- Goal: coercion of restrict(g₁*g₂) = coercion of (restrict(g₁) * restrict(g₂))
    simp only [LinearMap.restrict_coe_apply, Module.End.mul_apply] at h_mul ⊢
    exact h_mul

/-- The Schur module submodule is finite-dimensional. -/
instance schurModuleSubmodule_finite (k : Type*) [Field k] (N : ℕ) (lam : Fin N → ℕ) :
    Module.Finite k (SchurModuleSubmodule k N lam) :=
  inferInstance

/-- The Schur module `L_λ`: the irreducible polynomial representation of `GL_N(k)`
with highest weight `λ = (λ₁ ≥ ⋯ ≥ λ_N ≥ 0)`.

Constructed as the image of the Young symmetrizer `c_λ` acting on the tensor
power `(k^N)^{⊗n}` where `n = ∑ λᵢ`. The `GL_N(k)`-action is the restriction
of the diagonal action `g ↦ g^{⊗n}`, which commutes with the `S_n`-action
(and hence with `c_λ`), making the image `GL_N`-stable. -/
def SchurModule (k : Type*) [Field k] [IsAlgClosed k] (N : ℕ) (lam : Fin N → ℕ) :
    FDRep k (Matrix.GeneralLinearGroup (Fin N) k) :=
  FDRep.of (schurModuleRep k N lam)

/-! ### Diagonal torus and weight spaces -/

/-- The diagonal matrix in `GL_N(k)` with `t` at position `(i,i)` and `1` elsewhere.
This embeds a single coordinate of the maximal torus `(k×)^N ↪ GL_N(k)`. -/
noncomputable def diagUnit (k : Type*) [Field k] (N : ℕ) (i : Fin N) (t : kˣ) :
    Matrix.GeneralLinearGroup (Fin N) k where
  val := Matrix.diagonal (Function.update 1 i (t : k))
  inv := Matrix.diagonal (Function.update 1 i ((t⁻¹ : kˣ) : k))
  val_inv := by
    rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1; ext j
    by_cases h : j = i
    · subst h; simp [Units.val_inv_eq_inv_val]
    · simp [Function.update_of_ne h]
  inv_val := by
    rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1; ext j
    by_cases h : j = i
    · subst h; simp [Units.val_inv_eq_inv_val]
    · simp [Function.update_of_ne h]

/-- The weight space `M_μ` for weight `μ : Fin N → ℕ` in a `GL_N(k)`-representation `M`.
This is the subspace of `M` where the diagonal matrix with `t` at position `i`
acts as scalar multiplication by `t ^ μ i`, for each `i` and all `t ∈ k×`. -/
noncomputable def glWeightSpace (k : Type*) [Field k] [IsAlgClosed k] (N : ℕ)
    (M : FDRep k (Matrix.GeneralLinearGroup (Fin N) k))
    (μ : Fin N → ℕ) : Submodule k M :=
  ⨅ (i : Fin N) (t : kˣ),
    LinearMap.ker (M.ρ (diagUnit k N i t) - ((t : k) ^ μ i) • LinearMap.id)

/-! ### Diagonal matrices commute -/

/-- Diagonal matrices with entries modified at different positions commute. -/
theorem diagUnit_comm (k : Type*) [Field k] (N : ℕ) (i₁ : Fin N) (t₁ : kˣ)
    (i₂ : Fin N) (t₂ : kˣ) :
    diagUnit k N i₁ t₁ * diagUnit k N i₂ t₂ = diagUnit k N i₂ t₂ * diagUnit k N i₁ t₁ := by
  ext : 1
  change (diagUnit k N i₁ t₁).val * (diagUnit k N i₂ t₂).val =
    (diagUnit k N i₂ t₂).val * (diagUnit k N i₁ t₁).val
  simp only [diagUnit, Matrix.diagonal_mul_diagonal, mul_comm]

/-- The representation of two diagUnit elements commutes. -/
theorem rep_diagUnit_commute (k : Type*) [Field k] [IsAlgClosed k] (N : ℕ)
    (M : FDRep k (Matrix.GeneralLinearGroup (Fin N) k))
    (i₁ : Fin N) (t₁ : kˣ) (i₂ : Fin N) (t₂ : kˣ) :
    Commute (M.ρ (diagUnit k N i₁ t₁)) (M.ρ (diagUnit k N i₂ t₂)) := by
  change M.ρ (diagUnit k N i₁ t₁) * M.ρ (diagUnit k N i₂ t₂) =
    M.ρ (diagUnit k N i₂ t₂) * M.ρ (diagUnit k N i₁ t₁)
  rw [← map_mul, ← map_mul, diagUnit_comm]

/-! ### Weight space is contained in eigenspace -/

/-- The weight space is contained in the maximal generalized eigenspace of each
torus operator. Proved by extracting the (i, t) component from the iInf. -/
theorem glWeightSpace_le_maxGenEigenspace (k : Type*) [Field k] [IsAlgClosed k] (N : ℕ)
    (M : FDRep k (Matrix.GeneralLinearGroup (Fin N) k))
    (μ : Fin N → ℕ) (i : Fin N) (t : kˣ) :
    glWeightSpace k N M μ ≤
      Module.End.maxGenEigenspace (M.ρ (diagUnit k N i t)) ((t : k) ^ μ i) := by
  intro v hv
  -- Extract the (i, t) component: v ∈ ker(ρ(diagUnit i t) - t^(μ i) • id)
  have h1 : glWeightSpace k N M μ ≤ ⨅ (s : kˣ),
      LinearMap.ker (M.ρ (diagUnit k N i s) - ((s : k) ^ μ i) • LinearMap.id) :=
    iInf_le _ i
  have h2 : ⨅ (s : kˣ),
      LinearMap.ker (M.ρ (diagUnit k N i s) - ((s : k) ^ μ i) • LinearMap.id) ≤
      LinearMap.ker (M.ρ (diagUnit k N i t) - ((t : k) ^ μ i) • LinearMap.id) :=
    iInf_le _ t
  have hker := LinearMap.mem_ker.mp (h2 (h1 hv))
  -- hker says (ρ(diagUnit i t) - t^(μ i) • id) v = 0, so ρ(diagUnit i t) v = t^(μ i) • v
  have hev : (M.ρ (diagUnit k N i t)) v = ((t : k) ^ μ i) • v := by
    rwa [LinearMap.sub_apply, LinearMap.smul_apply, LinearMap.id_apply, sub_eq_zero] at hker
  -- This means v is an eigenvector, hence in the maxGenEigenspace
  exact Module.End.eigenspace_le_maxGenEigenspace (Module.End.mem_eigenspace_iff.mpr hev)

/-! ### Finiteness of weight support -/

/-- In an algebraically closed field (hence infinite), for any n ≥ 1 there exists
a unit t such that t^n ≠ 1. -/
theorem exists_unit_pow_ne_one (k : Type*) [Field k] [IsAlgClosed k] (n : ℕ) (hn : n ≥ 1) :
    ∃ t : kˣ, (t : k) ^ n ≠ 1 := by
  by_contra h; push_neg at h
  -- Every nonzero element of k is a root of X^n - C 1
  have hp_ne : (Polynomial.X ^ n - Polynomial.C (1 : k)) ≠ 0 :=
    Polynomial.X_pow_sub_C_ne_zero (by omega) 1
  -- The roots of X^n - 1 form a finite set
  have hfin : {a : k | a ^ n = 1}.Finite := by
    apply ((Polynomial.X ^ n - Polynomial.C (1 : k)).rootSet_finite k).subset
    intro a (ha : a ^ n = 1)
    rw [Polynomial.mem_rootSet]
    exact ⟨hp_ne, by simp [ha]⟩
  -- But every nonzero element of k satisfies x^n = 1
  have hsub : {a : k | a ≠ 0} ⊆ {a : k | a ^ n = 1} :=
    fun a ha => by simpa using h (Units.mk0 a ha)
  -- The set of nonzero elements is infinite (k is algebraically closed hence infinite)
  have hinf : Set.Infinite {a : k | a ≠ 0} := by
    rw [show {a : k | a ≠ 0} = ({0} : Set k)ᶜ from by ext; simp]
    exact (Set.finite_singleton _).infinite_compl
  exact hinf.not_finite (hfin.subset hsub)

/-- In an algebraically closed (hence infinite) field, distinct natural number exponents
give distinct power functions: if a ≠ b, there exists t ∈ kˣ with t^a ≠ t^b. -/
theorem exists_unit_pow_ne (k : Type*) [Field k] [IsAlgClosed k] {a b : ℕ} (hab : a ≠ b) :
    ∃ t : kˣ, (t : k) ^ a ≠ (t : k) ^ b := by
  -- Reduce to the case a > b
  suffices ∀ {a b : ℕ}, a > b → ∃ t : kˣ, (t : k) ^ a ≠ (t : k) ^ b from by
    rcases Nat.lt_or_gt_of_ne hab with h | h
    · obtain ⟨t, ht⟩ := this h; exact ⟨t, ht.symm⟩
    · exact this h
  intro a b h
  obtain ⟨t, ht⟩ := exists_unit_pow_ne_one k (a - b) (by omega)
  refine ⟨t, fun heq => ht ?_⟩
  have hne : (t : k) ^ b ≠ 0 := pow_ne_zero _ (Units.ne_zero t)
  have : (t : k) ^ (a - b) * (t : k) ^ b = 1 * (t : k) ^ b := by
    rw [← pow_add, Nat.sub_add_cancel h.le, heq, one_mul]
  exact mul_right_cancel₀ hne this

/-- The set of weights with nonzero weight space is finite for any finite-dimensional
`GL_N(k)`-representation. -/
theorem glWeightSpace_finite_support (k : Type*) [Field k] [IsAlgClosed k] (N : ℕ)
    (M : FDRep k (Matrix.GeneralLinearGroup (Fin N) k)) :
    { μ : Fin N →₀ ℕ | glWeightSpace k N M (fun i => μ i) ≠ ⊥ }.Finite := by
  -- Define the family of operators indexed by (Fin N × kˣ)
  set f : Fin N × kˣ → Module.End k M := fun p => M.ρ (diagUnit k N p.1 p.2) with hf_def
  -- The operators commute, so they satisfy the MapsTo condition
  have h_comm : ∀ (p₁ p₂ : Fin N × kˣ), Commute (f p₁) (f p₂) :=
    fun p₁ p₂ => rep_diagUnit_commute k N M p₁.1 p₁.2 p₂.1 p₂.2
  have h_mapsTo : ∀ (p₁ p₂ : Fin N × kˣ) (φ : k),
      Set.MapsTo (f p₁)
        ((f p₂).maxGenEigenspace φ) ((f p₂).maxGenEigenspace φ) :=
    fun p₁ p₂ φ => Module.End.mapsTo_maxGenEigenspace_of_comm (h_comm p₂ p₁) φ
  -- By Pi.lean, the simultaneous maximal generalized eigenspaces are independent
  have h_indep := Module.End.independent_iInf_maxGenEigenspace_of_forall_mapsTo f h_mapsTo
  -- By Noetherian, only finitely many are nonzero
  have h_fin := Submodule.finite_ne_bot_of_iSupIndep h_indep
  -- The weight space for μ is contained in the simultaneous maxGenEigenspace for χ_μ
  -- where χ_μ(i, t) = t^(μ i)
  -- Define the eigenvalue map
  set χ : (Fin N →₀ ℕ) → (Fin N × kˣ → k) :=
    fun μ p => (p.2 : k) ^ (μ p.1) with hχ_def
  -- Show the map is injective
  have h_inj : Function.Injective χ := by
    intro μ₁ μ₂ heq
    ext i
    by_contra hi
    obtain ⟨t, ht⟩ := exists_unit_pow_ne k hi
    exact ht (congr_fun heq (i, t))
  -- Show glWeightSpace μ ≤ ⨅ p, maxGenEigenspace(f p, χ μ p)
  have h_le : ∀ (μ : Fin N →₀ ℕ),
      glWeightSpace k N M (fun i => μ i) ≤
        ⨅ (p : Fin N × kˣ), (f p).maxGenEigenspace (χ μ p) := by
    intro μ
    apply le_iInf
    intro ⟨i, t⟩
    exact glWeightSpace_le_maxGenEigenspace k N M (fun j => μ j) i t
  -- If glWeightSpace μ ≠ ⊥, then the simultaneous maxGenEigenspace is also ≠ ⊥
  refine (h_fin.preimage h_inj.injOn).subset ?_
  intro μ hμ
  simp only [Set.mem_setOf_eq] at hμ
  simp only [Set.mem_preimage, Set.mem_setOf_eq]
  exact fun h => hμ (eq_bot_iff.mpr (h ▸ h_le μ))

/-! ### Formal character -/

/-- The formal character of a finite-dimensional polynomial `GL_N(k)`-representation,
as a polynomial in `N` variables over `ℚ`.

For a representation `M`, the formal character is `∑_μ (dim M_μ) · x^μ` where
`M_μ` is the weight space for weight `μ` under the diagonal torus action.
The sum ranges over the finitely many weights with nonzero weight space. -/
noncomputable def formalCharacter (k : Type*) [Field k] [IsAlgClosed k] (N : ℕ)
    (M : FDRep k (Matrix.GeneralLinearGroup (Fin N) k)) :
    MvPolynomial (Fin N) ℚ :=
  have hfin : { μ : Fin N →₀ ℕ |
      glWeightSpace k N M (fun i => μ i) ≠ ⊥ }.Finite :=
    glWeightSpace_finite_support k N M
  hfin.toFinset.sum fun μ =>
    (Module.finrank k (glWeightSpace k N M (fun i => μ i)) : ℚ) •
      MvPolynomial.monomial μ 1

variable (k : Type*) [Field k] [IsAlgClosed k]

/-! ### Coefficient extraction for formal character -/

/-- The coefficient of `x^μ` in the formal character equals the dimension of the weight space. -/
theorem formalCharacter_coeff (N : ℕ)
    (M : FDRep k (Matrix.GeneralLinearGroup (Fin N) k))
    (μ : Fin N →₀ ℕ) :
    (formalCharacter k N M).coeff μ =
      (Module.finrank k (glWeightSpace k N M (fun i => μ i)) : ℚ) := by
  unfold formalCharacter
  have key : ∀ (S : Finset (Fin N →₀ ℕ)) (c : (Fin N →₀ ℕ) → ℚ),
      (S.sum fun ν => c ν • MvPolynomial.monomial ν (1 : ℚ)).coeff μ =
        if μ ∈ S then c μ else 0 := by
    intro S c
    simp only [MvPolynomial.coeff_sum]
    simp_rw [MvPolynomial.coeff_smul, MvPolynomial.coeff_monomial, smul_eq_mul,
      mul_ite, mul_one, mul_zero]
    split_ifs with h
    · rw [Finset.sum_eq_single μ]
      · simp
      · intro ν _ hne; exact if_neg hne
      · intro h'; exact absurd h h'
    · exact Finset.sum_eq_zero fun ν hν => by
        rw [if_neg]; exact fun heq => h (heq ▸ hν)
  rw [key]
  split_ifs with hmem
  · rfl
  · have hbot : glWeightSpace k N M (fun i => μ i) = ⊥ := by
      by_contra h
      exact hmem ((glWeightSpace_finite_support k N M).mem_toFinset.mpr h)
    rw [hbot]; simp

/-! ### Weight multiplicity equals Schur polynomial coefficient -/

/-- **Key helper**: The dimension of the weight space for weight `μ` in the Schur module `L_λ`
equals the coefficient of `x^μ` in the Schur polynomial `S_λ`.

This is the core content of the Weyl character formula at the coefficient level:
`dim(L_λ)_μ = [x^μ] S_λ(x)`. -/
theorem schurModule_weight_eq_schurPoly_coeff
    (N : ℕ) (lam : Fin N → ℕ) (hlam : Antitone lam)
    (μ : Fin N →₀ ℕ) :
    (Module.finrank k (glWeightSpace k N (SchurModule k N lam) (fun i => μ i)) : ℚ) =
      (schurPoly N lam).coeff μ := by
  sorry

/-- **Weyl character formula for GL(V)**: the formal character of the Schur module
`L_λ` equals the Schur polynomial `S_λ(x₁, …, x_N)`.
(Etingof Theorem 5.22.1) -/
theorem Theorem5_22_1
    (N : ℕ) (lam : Fin N → ℕ) (hlam : Antitone lam) :
    formalCharacter k N (SchurModule k N lam) = schurPoly N lam := by
  ext μ
  rw [formalCharacter_coeff, schurModule_weight_eq_schurPoly_coeff k N lam hlam]

end Etingof
