import Mathlib
import EtingofRepresentationTheory.Chapter5.Definition5_12_1
import EtingofRepresentationTheory.Chapter5.Lemma5_13_2
import EtingofRepresentationTheory.Chapter5.Lemma5_13_3

/-!
# Theorem 5.12.2 (Part 1): Specht Module Definitions and Irreducibility

For each partition λ of n, the subspace V_λ = ℂ[S_n] · c_λ is an irreducible
representation of S_n (where c_λ is the Young symmetrizer).

## Mathlib correspondence

This is a fundamental classification theorem. Mathlib has `Nat.Partition` and
basic representation theory, but the Specht module construction and its
irreducibility are not yet formalized.
-/

namespace Etingof

/-- The group algebra ℂ[S_n]. -/
abbrev SymGroupAlgebra (n : ℕ) := MonoidAlgebra ℂ (Equiv.Perm (Fin n))

/-- The Specht module V_λ = ℂ[S_n] · c_λ, the left ideal of the group algebra
generated by the Young symmetrizer. (Etingof Definition following Theorem 5.12.2) -/
noncomputable def SpechtModule (n : ℕ) (la : Nat.Partition n) :
    Submodule (SymGroupAlgebra n) (SymGroupAlgebra n) :=
  Submodule.span (SymGroupAlgebra n) {YoungSymmetrizer n la}

noncomputable section
open scoped Classical

private abbrev G' (n : ℕ) := Equiv.Perm (Fin n)
private abbrev A' (n : ℕ) := MonoidAlgebra ℂ (G' n)

instance neZero_card_perm (n : ℕ) : NeZero (Nat.card (G' n) : ℂ) :=
  ⟨by exact_mod_cast Nat.card_pos.ne'⟩

/-- The sandwich property for the Young symmetrizer: c_λ * x * c_λ = f(x) • c_λ
for a linear functional f. This follows from Lemma 5.13.1 (a_λ * x * b_λ = ℓ(x) • c_λ). -/
private lemma sandwich_scalar (n : ℕ) (la : Nat.Partition n) :
    ∃ f : A' n →ₗ[ℂ] ℂ, ∀ x,
      YoungSymmetrizer n la * x * YoungSymmetrizer n la = f x • YoungSymmetrizer n la := by
  obtain ⟨ℓ, hℓ⟩ := Etingof.Lemma5_13_1 n la
  refine ⟨ℓ.comp ((LinearMap.mulLeft ℂ (ColumnAntisymmetrizer n la)).comp
    (LinearMap.mulRight ℂ (RowSymmetrizer n la))), fun x => ?_⟩
  change YoungSymmetrizer n la * x * YoungSymmetrizer n la =
    ℓ (ColumnAntisymmetrizer n la * (x * RowSymmetrizer n la)) • YoungSymmetrizer n la
  simp only [YoungSymmetrizer]
  have : RowSymmetrizer n la * ColumnAntisymmetrizer n la * x *
    (RowSymmetrizer n la * ColumnAntisymmetrizer n la) =
    RowSymmetrizer n la * (ColumnAntisymmetrizer n la * x * RowSymmetrizer n la) *
    ColumnAntisymmetrizer n la := by simp only [mul_assoc]
  rw [this, hℓ]; simp only [YoungSymmetrizer, mul_assoc]

/-- The trace of left multiplication by a MonoidAlgebra element in the regular
representation equals |G| times the coefficient of the identity element. -/
private lemma trace_lmul_monoidAlgebra
    {G : Type*} [Group G] [Fintype G]
    (a : MonoidAlgebra ℂ G) :
    LinearMap.trace ℂ (MonoidAlgebra ℂ G) (Algebra.lmul ℂ _ a) =
      Fintype.card G • a 1 := by
  classical
  rw [LinearMap.trace_eq_matrix_trace ℂ (MonoidAlgebra.basis G ℂ)]
  simp only [Matrix.trace, Matrix.diag_apply, LinearMap.toMatrix_apply,
    MonoidAlgebra.basis_apply]
  -- b.repr = id for MonoidAlgebra.basis, and lmul a x = a * x
  have : ∀ g : G, ((MonoidAlgebra.basis G ℂ).repr
    (Algebra.lmul ℂ (MonoidAlgebra ℂ G) a (MonoidAlgebra.single g 1))) g = a 1 := by
    intro g
    -- repr is identity for this basis; lmul a x = a * x
    change (a * MonoidAlgebra.single g 1 : G →₀ ℂ) g = (a : G →₀ ℂ) 1
    rw [MonoidAlgebra.mul_single_apply, mul_inv_cancel, mul_one]
  simp only [this, Finset.sum_const, Finset.card_univ]

/-- The sorted parts of a partition of n sum to n. -/
private lemma sortedParts_sum (n : ℕ) (la : Nat.Partition n) :
    la.sortedParts.sum = n := by
  have h := Multiset.sort_eq la.parts (· ≥ ·)
  have : (la.sortedParts : Multiset ℕ).sum = la.parts.sum := congrArg Multiset.sum h
  rw [Multiset.sum_coe] at this
  rw [this, la.parts_sum]

/-- A permutation that preserves both rows and columns must be the identity.
This follows from the injectivity of (rowOfPos, colOfPos) on valid positions. -/
private lemma row_col_inter_trivial (n : ℕ) (la : Nat.Partition n)
    (σ : Equiv.Perm (Fin n)) (hrow : σ ∈ RowSubgroup n la) (hcol : σ ∈ ColumnSubgroup n la) :
    σ = 1 := by
  ext k
  simp only [Equiv.Perm.one_apply]
  have hsum : la.sortedParts.sum = n := sortedParts_sum n la
  have hk : k.val < la.sortedParts.sum := by rw [hsum]; exact k.isLt
  have hσk : (σ k).val < la.sortedParts.sum := by rw [hsum]; exact (σ k).isLt
  exact rowOfPos_colOfPos_injective la.sortedParts
    (σ k).val k.val hσk hk (hrow k) (hcol k)

/-- The ColumnAntisymmetrizer evaluated at σ ∈ Q_λ gives sign(σ). -/
private lemma columnAntisymmetrizer_apply_mem (n : ℕ) (la : Nat.Partition n) (σ : G' n)
    (hσ : σ ∈ ColumnSubgroup n la) :
    (ColumnAntisymmetrizer n la : A' n) σ = ((↑(Equiv.Perm.sign σ) : ℤ) : ℂ) := by
  simp only [ColumnAntisymmetrizer, MonoidAlgebra.of_apply]
  rw [Finsupp.finset_sum_apply]
  rw [Finset.sum_congr rfl (fun i _ => show _ = _ from by
    change ((↑(↑(Equiv.Perm.sign (i : G' n)) : ℤ) : ℂ) • (Finsupp.single (i : G' n) (1 : ℂ))) σ = _
    rw [Finsupp.smul_apply, smul_eq_mul, Finsupp.single_apply])]
  rw [Finset.sum_eq_single (⟨σ, hσ⟩ : ↑(ColumnSubgroup n la))]
  · simp
  · intro q _ hq
    have : (q : G' n) ≠ σ := fun h => hq (Subtype.ext h)
    simp [this]
  · intro h; exact absurd (Finset.mem_univ _) h

/-- The ColumnAntisymmetrizer evaluated at σ ∉ Q_λ gives 0. -/
private lemma columnAntisymmetrizer_apply_not_mem (n : ℕ) (la : Nat.Partition n) (σ : G' n)
    (hσ : σ ∉ ColumnSubgroup n la) :
    (ColumnAntisymmetrizer n la : A' n) σ = 0 := by
  simp only [ColumnAntisymmetrizer, MonoidAlgebra.of_apply]
  rw [Finsupp.finset_sum_apply]
  rw [Finset.sum_congr rfl (fun i _ => show _ = _ from by
    change ((↑(↑(Equiv.Perm.sign (i : G' n)) : ℤ) : ℂ) • (Finsupp.single (i : G' n) (1 : ℂ))) σ = _
    rw [Finsupp.smul_apply, smul_eq_mul, Finsupp.single_apply])]
  apply Finset.sum_eq_zero
  intro q _
  have : (q : G' n) ≠ σ := fun h => hσ (h ▸ q.prop)
  simp [this]

/-- The coefficient of the identity permutation in the Young symmetrizer is 1.
This uses the fact that P_λ ∩ Q_λ = {id}: only the pair (id, id) in P × Q
maps to the identity permutation. -/
private lemma youngSymmetrizer_identity_coeff (n : ℕ) (la : Nat.Partition n) :
    (YoungSymmetrizer n la : A' n) 1 = 1 := by
  simp only [YoungSymmetrizer, RowSymmetrizer, MonoidAlgebra.of_apply, Finset.sum_mul]
  rw [Finsupp.finset_sum_apply]
  simp only [MonoidAlgebra.single_mul_apply, one_mul, mul_one]
  -- Goal: ∑ p : RowSubgroup, (ColAnti)(p⁻¹) = 1
  rw [Finset.sum_eq_single (⟨1, (RowSubgroup n la).one_mem⟩ : ↑(RowSubgroup n la))]
  · -- p = 1: ColAnti(1⁻¹) = ColAnti(1) = sign(1) = 1
    simp only [Subgroup.coe_mk, inv_one]
    rw [columnAntisymmetrizer_apply_mem n la 1 (ColumnSubgroup n la).one_mem]
    simp [Equiv.Perm.sign_one]
  · -- p ≠ 1: ColAnti(p⁻¹) = 0
    intro p _ hp
    have hp_ne : (p : G' n) ≠ 1 := fun h => hp (Subtype.ext h)
    apply columnAntisymmetrizer_apply_not_mem
    intro hcol
    exact hp_ne (row_col_inter_trivial n la p.val p.prop
      ((ColumnSubgroup n la).inv_mem_iff.mp hcol))
  · intro h; exact absurd (Finset.mem_univ _) h

/-- c_λ² ≠ 0. Proved via the trace argument: if c_λ² = 0 then left multiplication
L_{c_λ} is nilpotent, so its trace is 0. But Tr(L_{c_λ}) = n! · c_λ(e) = n! ≠ 0. -/
lemma young_symmetrizer_sq_ne_zero (n : ℕ) (la : Nat.Partition n) :
    YoungSymmetrizer n la * YoungSymmetrizer n la ≠ 0 := by
  set c := YoungSymmetrizer n la
  intro h_sq_zero
  -- Left multiplication by c is nilpotent (L_c² = L_{c²} = 0)
  set L : A' n →ₗ[ℂ] A' n := LinearMap.mulLeft ℂ c
  have h_nilp : IsNilpotent L := by
    refine ⟨2, LinearMap.ext fun x => ?_⟩
    change L (L x) = 0
    simp only [L, LinearMap.mulLeft_apply, ← mul_assoc, h_sq_zero, zero_mul]
  -- Trace of nilpotent is nilpotent in ℂ, hence 0
  have h_tr_nilp := LinearMap.isNilpotent_trace_of_isNilpotent h_nilp
  have h_tr_zero : LinearMap.trace ℂ (A' n) L = 0 :=
    isNilpotent_iff_eq_zero.mp h_tr_nilp
  -- But L = Algebra.lmul ℂ _ c, so trace = n! · c(e) = n! ≠ 0
  have hL : L = Algebra.lmul ℂ (A' n) c := rfl
  rw [hL, trace_lmul_monoidAlgebra, youngSymmetrizer_identity_coeff] at h_tr_zero
  simp only [nsmul_eq_mul, mul_one] at h_tr_zero
  have : (Fintype.card (G' n) : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr Fintype.card_pos.ne'
  exact this h_tr_zero

/-- The Specht module V_λ is an irreducible (simple) left ℂ[S_n]-module.
(Etingof Theorem 5.12.2, part 1)

The proof uses:
- Lemma 5.13.3: c_λ² = α • c_λ for some scalar α
- The sandwich property: c_λ * x * c_λ = f(x) • c_λ for a linear functional f
- Maschke's theorem: ℂ[S_n] is semisimple, so any submodule has a complement
- For any proper submodule N < V_λ, decompose c_λ = n₀ + p₀ with n₀ ∈ N, p₀ ∈ P
  (complement). The sandwich property forces either c_λ ∈ N (contradiction with
  N being proper) or n₀ = 0 and c_λ ∈ P (contradiction with N ≠ ⊥). -/
theorem Theorem5_12_2_irreducible
    (n : ℕ) (la : Nat.Partition n) :
    IsSimpleModule (SymGroupAlgebra n) (SpechtModule n la) := by
  rw [isSimpleModule_iff_isAtom]
  obtain ⟨α, hα_eq⟩ := Etingof.Lemma5_13_3 n la
  have hα_ne : α ≠ 0 := fun h => young_symmetrizer_sq_ne_zero n la (by rw [hα_eq, h, zero_smul])
  obtain ⟨f, hf⟩ := sandwich_scalar n la
  set c := YoungSymmetrizer n la with hc_def
  refine ⟨?_, ?_⟩
  · -- SpechtModule ≠ ⊥
    intro h
    have hc_zero : (c : A' n) = 0 :=
      (Submodule.mem_bot (R := A' n)).mp (h ▸ Submodule.subset_span rfl)
    exact young_symmetrizer_sq_ne_zero n la (show c * c = 0 by rw [hc_zero, mul_zero])
  · -- ∀ N < SpechtModule, N = ⊥
    intro N hN
    by_contra hN_ne_bot
    have hN_le := le_of_lt hN
    suffices c ∈ N by
      exact ne_of_lt hN
        (le_antisymm hN_le (Submodule.span_le.mpr (Set.singleton_subset_iff.mpr this)))
    obtain ⟨P, hP⟩ := (inferInstance : IsSemisimpleModule (A' n) (A' n)).exists_isCompl N
    obtain ⟨n₀, hn₀, p₀, hp₀, hc_eq⟩ := Submodule.mem_sup.mp
      (show c ∈ N ⊔ P from hP.sup_eq_top ▸ Submodule.mem_top)
    obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp
      (show n₀ ∈ SpechtModule n la from hN_le hn₀)
    have hcn₀ : c * n₀ = f a • c := by
      rw [← ha]; change c * (a * c) = _; rw [← mul_assoc]; exact hf a
    have hcn₀_N : c * n₀ ∈ N := N.smul_mem _ hn₀
    by_cases hfa : f a = 0
    · rw [hfa, zero_smul] at hcn₀
      have hcc_cp₀ : c * c = c * p₀ := by
        calc c * c = c * (n₀ + p₀) := by rw [hc_eq]
          _ = c * n₀ + c * p₀ := mul_add _ _ _
          _ = c * p₀ := by rw [hcn₀, zero_add]
      have hαc_P : α • c ∈ P := by rw [← hα_eq, hcc_cp₀]; exact P.smul_mem _ hp₀
      have h1 : α • n₀ ∈ N := Submodule.smul_of_tower_mem N α hn₀
      have h2 : α • n₀ ∈ P := by
        rw [show α • n₀ = α • c - α • p₀ from by rw [← hc_eq, smul_add, add_sub_cancel_right]]
        exact P.sub_mem hαc_P (Submodule.smul_of_tower_mem P α hp₀)
      have h3 : α • n₀ = 0 :=
        (Submodule.mem_bot (R := A' n)).mp (hP.inf_eq_bot ▸ Submodule.mem_inf.mpr ⟨h1, h2⟩)
      have hn₀_zero : n₀ = 0 := (smul_eq_zero.mp h3).resolve_left hα_ne
      exfalso; apply hN_ne_bot; rw [eq_bot_iff]; intro x hx
      have hc_P : c ∈ P := by rw [← hc_eq, hn₀_zero, zero_add]; exact hp₀
      have hV_le_P : SpechtModule n la ≤ P :=
        Submodule.span_le.mpr (Set.singleton_subset_iff.mpr hc_P)
      exact (Submodule.mem_bot (R := A' n)).mpr
        ((Submodule.mem_bot (R := A' n)).mp
          (hP.inf_eq_bot ▸ Submodule.mem_inf.mpr ⟨hx, hV_le_P (hN_le hx)⟩))
    · rw [hcn₀] at hcn₀_N
      rw [show c = (f a)⁻¹ • (f a • c) from by rw [inv_smul_smul₀ hfa]]
      exact Submodule.smul_of_tower_mem N (f a)⁻¹ hcn₀_N

end

end Etingof
