import Mathlib

/-!
# Theorem 5.18.2: End_A(E) as Image of Universal Enveloping Algebra

The algebra End_A(E), where A = Im(ℂ[S_n] → End(V^⊗n)), equals the image of
U(gl(V)) in End(V^⊗n). It is generated by elements of the form:

  Δ_n(b) = b⊗1⊗...⊗1 + 1⊗b⊗...⊗1 + ... + 1⊗...⊗1⊗b

for b ∈ gl(V). This connects the centralizer of the symmetric group action
to the Lie algebra action.

## Mathlib correspondence

- `UniversalEnvelopingAlgebra R L` for U(gl(V))
- `PiTensorProduct` / `TensorPower` for V^⊗n
- `Subalgebra.centralizer` for the centralizer
- `AlgHom.range` for the image subalgebra
-/

open scoped TensorProduct

namespace Etingof.Theorem5_18_2

variable (k : Type*) [Field k]
  (V : Type*) [AddCommGroup V] [Module k V] [Module.Finite k V]
  (n : ℕ)

/-- The n-th tensor power V^⊗n. -/
abbrev TnsPow := ⨂[k] (_ : Fin n), V

/-- The diagonal Lie algebra action of gl(V) on V^⊗n.
Sends b ∈ gl(V) = End_k(V) to Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1),
where b appears in position i and identity elsewhere. -/
noncomputable def diagonalLieAction :
    Module.End k V →ₗ⁅k⁆ Module.End k (TnsPow k V n) where
  toLinearMap :=
    { toFun := fun b => ∑ i : Fin n,
        PiTensorProduct.map (fun j => if j = i then b else LinearMap.id)
      map_add' := sorry
      map_smul' := sorry }
  map_lie' := sorry

/-- The algebra homomorphism from U(gl(V)) to End(V^⊗n) induced by the
diagonal Lie algebra action. By the universal property, the Lie algebra
morphism gl(V) →ₗ⁅k⁆ End(V^⊗n) lifts uniquely to an algebra map. -/
noncomputable def universalEnvelopingToEnd :
    UniversalEnvelopingAlgebra k (Module.End k V) →ₐ[k]
      Module.End k (TnsPow k V n) :=
  UniversalEnvelopingAlgebra.lift k (diagonalLieAction k V n)

/-- The image of k[S_n] in End(V^⊗n), defined as the subalgebra
generated by the symmetric group action (permuting tensor factors). -/
noncomputable def symGroupImage :
    Subalgebra k (Module.End k (TnsPow k V n)) :=
  Algebra.adjoin k (Set.range fun (σ : Equiv.Perm (Fin n)) =>
    (PiTensorProduct.reindex k (fun _ => V) σ).toLinearMap)

/-- The centralizer of ℂ[S_n] acting on V^⊗n is the image of U(gl(V)).

The centralizer End_{ℂ[S_n]}(V^⊗n) — the subalgebra of End(V^⊗n) commuting
with every permutation operator — equals the image of the natural algebra
map U(gl(V)) → End(V^⊗n) induced by the diagonal Lie action
b ↦ Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1).

(Etingof Theorem 5.18.2) -/
theorem centralizer_eq_universalEnvelopingImage :
    Subalgebra.centralizer k
      (symGroupImage k V n : Set (Module.End k (TnsPow k V n))) =
    (universalEnvelopingToEnd k V n).range := by
  sorry

end Etingof.Theorem5_18_2
