import Mathlib

/-!
# Theorem 5.18.2: End_A(E) as Image of Universal Enveloping Algebra

The algebra End_A(E), where A = Im(ℂ[S_n] → End(V^⊗n)), equals the image of
U(gl(V)) in End(V^⊗n). It is generated by elements of the form:

  Δ_n(b) = b⊗1⊗...⊗1 + 1⊗b⊗...⊗1 + ... + 1⊗...⊗1⊗b

for b ∈ gl(V). This connects the centralizer of the symmetric group action
to the Lie algebra action.

## Mathlib correspondence

Requires tensor power modules, universal enveloping algebras, and the
interaction between S_n and gl(V) actions on V^⊗n.
-/

/-- The centralizer of ℂ[S_n] acting on V^⊗n is the image of U(gl(V)).
(Etingof Theorem 5.18.2) -/
theorem Etingof.Theorem5_18_2
    (k : Type*) [Field k]
    (V : Type*) [AddCommGroup V] [Module k V] [Module.Finite k V]
    (n : ℕ) :
    -- End_{ℂ[S_n]}(V^⊗n) = Im(U(gl(V)) → End(V^⊗n))
    (sorry : Prop) := by
  sorry
