import Mathlib
import EtingofRepresentationTheory.Chapter5.Lemma5_18_3

/-!
# Theorem 5.18.2: End_A(E) as Image of Universal Enveloping Algebra

The algebra End_A(E), where A = Im(ℂ[S_n] → End(V^⊗n)), equals the image of
U(gl(V)) in End(V^⊗n). It is generated by elements of the form:

  Δ_n(b) = b⊗1⊗...⊗1 + 1⊗b⊗...⊗1 + ... + 1⊗...⊗1⊗b

for b ∈ gl(V). This connects the centralizer of the symmetric group action
to the Lie algebra action.

## Mathlib correspondence

- `UniversalEnvelopingAlgebra R L` for U(gl(V))
- `PiTensorProduct` / `TensorPower` for V^⊗n
- `Subalgebra.centralizer` for the centralizer
- `AlgHom.range` for the image subalgebra
-/

open scoped TensorProduct

namespace Etingof.Theorem5_18_2

variable (k : Type*) [Field k]
  (V : Type*) [AddCommGroup V] [Module k V] [Module.Finite k V]
  (n : ℕ)

/-- The n-th tensor power V^⊗n. -/
abbrev TnsPow := ⨂[k] (_ : Fin n), V

/-- The diagonal Lie algebra action of gl(V) on V^⊗n.
Sends b ∈ gl(V) = End_k(V) to Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1),
where b appears in position i and identity elsewhere. -/
noncomputable def diagonalLieAction :
    Module.End k V →ₗ⁅k⁆ Module.End k (TnsPow k V n) where
  toLinearMap :=
    { toFun := fun b => ∑ i : Fin n,
        PiTensorProduct.map (fun j => if j = i then b else LinearMap.id)
      map_add' := by
        intro b₁ b₂
        have key : ∀ (i : Fin n) (b : Module.End k V),
            (fun j => if j = i then b else LinearMap.id) =
            Function.update (fun _ => LinearMap.id) i b := by
          intro i b; ext j; simp [Function.update, eq_comm]
        simp_rw [key]
        rw [← Finset.sum_add_distrib]
        congr 1; ext i
        rw [PiTensorProduct.map_update_add]
      map_smul' := by
        intro c b
        have key : ∀ (i : Fin n) (b : Module.End k V),
            (fun j => if j = i then b else LinearMap.id) =
            Function.update (fun _ => LinearMap.id) i b := by
          intro i b; ext j; simp [Function.update, eq_comm]
        simp_rw [key]
        rw [show RingHom.id k c = c from rfl, Finset.smul_sum]
        congr 1; ext i
        rw [PiTensorProduct.map_update_smul] }
  map_lie' := by
    intro b₁ b₂
    have key : ∀ (i : Fin n) (b : Module.End k V),
        (fun j => if j = i then b else LinearMap.id) =
        Function.update (fun _ => LinearMap.id) i b := by
      intro i b; ext j; simp [Function.update, eq_comm]
    simp_rw [key]
    simp only [LieRing.of_associative_ring_bracket]
    -- LHS: ∑ᵢ map(δᵢ(b₁*b₂ - b₂*b₁))
    -- Step 1: Reduce to ∑ᵢ (map(δᵢ(b₁)) * map(δᵢ(b₂)) - map(δᵢ(b₂)) * map(δᵢ(b₁)))
    -- Helper: map_mul for our specific type family
    set δ := fun (i : Fin n) (b : Module.End k V) =>
      PiTensorProduct.map (R := k) (s := fun _ => V) (t := fun _ => V)
        (Function.update (fun _ => LinearMap.id) i b) with hδ
    -- Step 1: δ i b₁ * δ j b₂ = δ of composed updates (via map_mul)
    have mul_eq : ∀ (i j : Fin n) (a b : Module.End k V),
        δ i a * δ j b = PiTensorProduct.map
          (fun l => Function.update (fun _ => LinearMap.id) i a l *
                    Function.update (fun _ => LinearMap.id) j b l) := by
      intro i j a b; exact (PiTensorProduct.map_mul _ _).symm
    -- Helper: δ respects sub (from multilinear structure)
    have δ_sub : ∀ (i : Fin n) (a b : Module.End k V),
        δ i (a - b) = δ i a - δ i b := by
      intro i a b
      simp only [hδ]
      exact (PiTensorProduct.mapMultilinear (R := k) (s := fun _ => V)
        (t := fun _ => V)).map_update_sub (fun _ => LinearMap.id) i a b
    -- Helper: δ preserves mul (update id i (a*b) = (update id i a) * (update id i b) pointwise)
    have δ_mul : ∀ (i : Fin n) (a b : Module.End k V),
        δ i (a * b) = δ i a * δ i b := by
      intro i a b
      simp only [hδ, ← PiTensorProduct.map_mul]
      congr 1; funext l
      by_cases h : l = i <;>
        simp [Function.update, h, Module.End.mul_eq_comp, LinearMap.comp_id]
    -- Step 2: Each LHS summand equals diagonal term
    have lhs_eq : ∀ i : Fin n,
        δ i (b₁ * b₂ - b₂ * b₁) = δ i b₁ * δ i b₂ - δ i b₂ * δ i b₁ := by
      intro i; rw [δ_sub, δ_mul, δ_mul]
    rw [Finset.sum_congr rfl (fun i _ => lhs_eq i)]
    -- Step 3: Cross-terms (i ≠ j) commute
    have comm : ∀ i j : Fin n, i ≠ j → δ i b₁ * δ j b₂ = δ j b₂ * δ i b₁ := by
      intro i j hij
      simp only [hδ, ← PiTensorProduct.map_mul]
      congr 1; funext l
      by_cases hi : l = i <;> by_cases hj : l = j <;>
        simp [Function.update, hi, hj, hij, Ne.symm hij,
          Module.End.mul_eq_comp, LinearMap.comp_id, LinearMap.id_comp]
    -- Step 4: Expand RHS to double sum, show cross-terms vanish
    rw [Finset.sum_mul_sum, Finset.sum_mul_sum]
    rw [Finset.sum_comm (f := fun j i => δ j b₂ * δ i b₁)]
    rw [← Finset.sum_sub_distrib]
    simp_rw [← Finset.sum_sub_distrib]
    -- ∑ᵢ∑ⱼ (δᵢb₁*δⱼb₂ - δⱼb₂*δᵢb₁). Cross-terms (i≠j) vanish.
    apply Finset.sum_congr rfl; intro i _
    symm
    exact Finset.sum_eq_single i
      (fun j _ hji => sub_eq_zero.mpr (comm i j hji.symm))
      (fun h => absurd (Finset.mem_univ _) h)

/-- The algebra homomorphism from U(gl(V)) to End(V^⊗n) induced by the
diagonal Lie algebra action. By the universal property, the Lie algebra
morphism gl(V) →ₗ⁅k⁆ End(V^⊗n) lifts uniquely to an algebra map. -/
noncomputable def universalEnvelopingToEnd :
    UniversalEnvelopingAlgebra k (Module.End k V) →ₐ[k]
      Module.End k (TnsPow k V n) :=
  UniversalEnvelopingAlgebra.lift k (diagonalLieAction k V n)

/-- The image of k[S_n] in End(V^⊗n), defined as the subalgebra
generated by the symmetric group action (permuting tensor factors). -/
noncomputable def symGroupImage :
    Subalgebra k (Module.End k (TnsPow k V n)) :=
  Algebra.adjoin k (Set.range fun (σ : Equiv.Perm (Fin n)) =>
    (PiTensorProduct.reindex k (fun _ => V) σ).toLinearMap)

omit [Module.Finite k V] in
/-- The diagonal Lie action of b ∈ gl(V) commutes with permutation of tensor factors. -/
private lemma diagonalLieAction_commutes_reindex (b : Module.End k V)
    (σ : Equiv.Perm (Fin n)) :
    diagonalLieAction k V n b *
      (PiTensorProduct.reindex k (fun _ : Fin n => V) σ).toLinearMap =
    (PiTensorProduct.reindex k (fun _ : Fin n => V) σ).toLinearMap *
      diagonalLieAction k V n b := by
  simp only [diagonalLieAction, LieHom.coe_mk]
  rw [Finset.sum_mul, Finset.mul_sum]
  apply Finset.sum_nbij σ.symm
  · exact fun _ _ => Finset.mem_univ _
  · exact σ.symm.injective.injOn
  · exact fun i _ => ⟨σ i, by simp, σ.symm_apply_apply i⟩
  · intro i _
    rw [Module.End.mul_eq_comp, Module.End.mul_eq_comp]
    -- Goal: map(δᵢ b) ∘ₗ reindex σ = reindex σ ∘ₗ map(δ_{σ⁻¹ i} b)
    -- map_comp_reindex_eq with f = δ_{σ⁻¹ i} b gives the result
    -- since (δ_{σ⁻¹ i} b)(σ⁻¹ j) = δᵢ b j by injectivity
    rw [← PiTensorProduct.map_comp_reindex_eq]
    congr 1; congr 1; funext j
    simp

/-- The centralizer of ℂ[S_n] acting on V^⊗n is the image of U(gl(V)).

The centralizer End_{ℂ[S_n]}(V^⊗n) — the subalgebra of End(V^⊗n) commuting
with every permutation operator — equals the image of the natural algebra
map U(gl(V)) → End(V^⊗n) induced by the diagonal Lie action
b ↦ Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1).

(Etingof Theorem 5.18.2) -/
theorem centralizer_eq_universalEnvelopingImage :
    Subalgebra.centralizer k
      (symGroupImage k V n : Set (Module.End k (TnsPow k V n))) =
    (universalEnvelopingToEnd k V n).range := by
  apply le_antisymm
  · -- (⊆) centralizer ≤ range: textbook proof (Etingof 5.18.2)
    -- B = S^n End(V) by definition, generated by Δ_n(b) by Lemma 5.18.3(ii).
    -- Step 1: centralizer of S_n in End(V^⊗n) ⊆ S^n End(V)
    -- (the full diagonal subalgebra generated by f ⊗ f ⊗ ... ⊗ f)
    have h_cent_full : Subalgebra.centralizer k
        (symGroupImage k V n : Set (Module.End k (TnsPow k V n))) ≤
        Lemma5_18_3.fullDiagonalSubalgebra k V n := by
      sorry -- Requires: End(V^⊗n) ≅ End(V)^⊗n, centralizer of S_n = symmetric part
    -- Step 2: S^n End(V) ⊆ subalgebra generated by Δ_n(b) (Lemma 5.18.3 part ii)
    -- Note: diagonalSubalgebra_eq_fullDiagonal requires CharZero k
    have h_full_diag : Lemma5_18_3.fullDiagonalSubalgebra k V n ≤
        Lemma5_18_3.diagonalSubalgebra k V n := by
      -- Requires CharZero k (holds for ℂ); use diagonalSubalgebra_eq_fullDiagonal
      sorry
    -- Step 3: each Δ_n(b) generator is in the range of U(gl(V))
    have h_diag_range : Lemma5_18_3.diagonalSubalgebra k V n ≤
        (universalEnvelopingToEnd k V n).range := by
      apply Algebra.adjoin_le
      rintro _ ⟨b, rfl⟩
      exact (universalEnvelopingToEnd k V n).mem_range.mpr
        ⟨UniversalEnvelopingAlgebra.ι k b,
          UniversalEnvelopingAlgebra.lift_ι_apply k (diagonalLieAction k V n) b⟩
    exact (h_cent_full.trans h_full_diag).trans h_diag_range
  · -- (⊇) range ≤ centralizer: image of U(gl(V)) commutes with S_n action
    -- Flip: equivalently, symGroupImage ≤ centralizer(range)
    rw [Subalgebra.le_centralizer_iff]
    -- symGroupImage is adjoin of generators, use adjoin_le
    apply Algebra.adjoin_le
    rintro _ ⟨σ, rfl⟩
    rw [SetLike.mem_coe, Subalgebra.mem_centralizer_iff]
    intro x hx
    obtain ⟨y, rfl⟩ := (universalEnvelopingToEnd k V n).mem_range.mp hx
    -- Show: reindex σ commutes with universalEnvelopingToEnd y
    -- Use hom_ext: conjugation by reindex σ fixes universalEnvelopingToEnd
    set e := PiTensorProduct.reindex k (fun _ : Fin n => V) σ
    -- Key: conjAlgEquiv e composed with universalEnvelopingToEnd equals
    -- universalEnvelopingToEnd (they agree on ι by the helper lemma)
    have hext : (e.conjAlgEquiv k).toAlgHom.comp
        (universalEnvelopingToEnd k V n) =
        universalEnvelopingToEnd k V n := by
      apply UniversalEnvelopingAlgebra.hom_ext; ext1 b
      simp only [LieHom.comp_apply, AlgHom.toLieHom_apply,
        AlgHom.comp_apply, AlgEquiv.toAlgHom_eq_coe,
        AlgHom.coe_coe, LinearEquiv.conjAlgEquiv_apply,
        universalEnvelopingToEnd,
        UniversalEnvelopingAlgebra.lift_ι_apply]
      -- Goal: e ∘ₗ diag b ∘ₗ e.symm = diag b
      -- From helper: diag b * ↑e = ↑e * diag b (commutation)
      have h := diagonalLieAction_commutes_reindex k V n b σ
      -- In Module.End mul terms:
      -- (↑e * diag b) * ↑e.symm = diag b * (↑e * ↑e.symm) = diag b
      have he_inv : (↑e : Module.End k (TnsPow k V n)) *
          ↑e.symm = 1 := by
        ext v; simp [Module.End.mul_eq_comp]
      -- conjAlgEquiv e (diag b) = ↑e * diag b * ↑e.symm
      -- But ∘ₗ is the same as * in Module.End
      change ↑e * diagonalLieAction k V n b * ↑e.symm =
        diagonalLieAction k V n b
      rw [h.symm, mul_assoc, he_inv, mul_one]
    -- Extract: conjAlgEquiv e (universalEnvelopingToEnd y) =
    --   universalEnvelopingToEnd y
    have key := AlgHom.congr_fun hext y
    simp only [AlgHom.comp_apply, AlgEquiv.toAlgHom_eq_coe,
      AlgHom.coe_coe, LinearEquiv.conjAlgEquiv_apply] at key
    -- key : ↑e * universalEnvelopingToEnd y * ↑e.symm =
    --        universalEnvelopingToEnd y
    -- Derive commutation: ↑e * f = f * ↑e
    -- Convert key to * notation: ↑e * f * ↑e.symm = f
    have key_mul : (↑e : Module.End k (TnsPow k V n)) *
        (universalEnvelopingToEnd k V n) y * ↑e.symm =
        (universalEnvelopingToEnd k V n) y := by
      simp only [Module.End.mul_eq_comp]; exact key
    have he_inv : (↑e.symm : Module.End k (TnsPow k V n)) *
        ↑e = 1 := by
      ext v; simp [Module.End.mul_eq_comp]
    -- Multiply key_mul on right by ↑e: ↑e * f * ↑e.symm * ↑e = f * ↑e
    -- Use assoc: ↑e * f * (↑e.symm * ↑e) = f * ↑e, then he_inv
    have := congr_arg (· * (↑e : Module.End k _)) key_mul
    simp only [mul_assoc, he_inv, mul_one] at this
    exact this.symm

end Etingof.Theorem5_18_2
