import Mathlib
import EtingofRepresentationTheory.Chapter5.Theorem5_18_1
import EtingofRepresentationTheory.Chapter5.Theorem5_18_2
import EtingofRepresentationTheory.Chapter5.Lemma5_18_3

/-!
# Theorem 5.18.4: Schur-Weyl Duality

The fundamental Schur-Weyl duality theorem for V^⊗n:

(i) Let A = Im(k[S_n] → End(V^⊗n)) and B = Im(U(gl(V)) → End(V^⊗n)).
    Then A = End_B(V^⊗n) and B = End_A(V^⊗n).

(ii) Both A and B are semisimple, and V^⊗n is a semisimple gl(V)-module.

(iii) As an (A ⊗ B)-module:
      V^⊗n ≅ ⊕ Vpart ⊗ Lpart
      where Vpart ranges over Specht modules of S_n and Lpart are the
      corresponding irreducible polynomial representations of GL(V).

## Mathlib correspondence

Schur-Weyl duality is a deep theorem connecting representation theory of S_n
and GL(V). We use `PiTensorProduct` for V^⊗n, `MonoidAlgebra` for k[S_n],
and `Subalgebra.centralizer` for the commutant.
-/

open scoped TensorProduct

namespace Etingof

universe u v

variable (k : Type u) [Field k]
  (V : Type v) [AddCommGroup V] [Module k V] [Module.Finite k V]
  (n : ℕ)

/-- The n-th tensor power V^⊗n as a type. -/
abbrev TensorPower := ⨂[k] (_ : Fin n), V

/-- The tensor power of a finite-dimensional module is finite-dimensional.
This follows from the fact that if V has a finite basis, then V⊗ⁿ has a
basis indexed by n-tuples of basis elements. -/
instance tensorPower_finite : Module.Finite k (TensorPower k V n) := by
  haveI : Module.Free k V := Module.Free.of_divisionRing k V
  let b := Module.Free.chooseBasis k V
  exact Module.Finite.of_basis (Basis.piTensorProduct (fun _ : Fin n => b))

/-- The symmetric group action on V^⊗n by permuting tensor factors.
Given σ ∈ S_n, this sends v₁ ⊗ ... ⊗ vₙ to v_{σ⁻¹(1)} ⊗ ... ⊗ v_{σ⁻¹(n)}.
This is a linear equivalence, hence an element of End_k(V^⊗n). -/
noncomputable def symGroupAction (σ : Equiv.Perm (Fin n)) :
    TensorPower k V n ≃ₗ[k] TensorPower k V n :=
  PiTensorProduct.reindex k (fun _ => V) σ

/-- The image of k[S_n] in End(V^⊗n), defined as the subalgebra
generated by the symmetric group action on tensor factors.

This is the subalgebra of End_k(V^⊗n) generated by all permutation
operators σ : V^⊗n → V^⊗n for σ ∈ S_n. -/
noncomputable def symGroupImage :
    Subalgebra k (Module.End k (TensorPower k V n)) :=
  Algebra.adjoin k (Set.range fun (σ : Equiv.Perm (Fin n)) =>
    (symGroupAction k V n σ).toLinearMap)

/-- The diagonal action subalgebra: the image of the diagonal action of
End_k(V) on V^⊗n, where f ∈ End_k(V) acts as f ⊗ f ⊗ ... ⊗ f.
This is the subalgebra generated by the image of GL(V) (equivalently,
the image of the universal enveloping algebra U(gl(V))). -/
noncomputable def diagonalActionImage :
    Subalgebra k (Module.End k (TensorPower k V n)) :=
  Algebra.adjoin k (Set.range fun (f : Module.End k V) =>
    PiTensorProduct.map (fun _ => f))

/-- Permutation and diagonal operators commute:
(reindex σ) ∘ (map f) = (map f) ∘ (reindex σ). -/
theorem symGroupAction_comm_diagonalAction (σ : Equiv.Perm (Fin n)) (f : Module.End k V) :
    (symGroupAction k V n σ).toLinearMap ∘ₗ PiTensorProduct.map (fun _ => f) =
    PiTensorProduct.map (fun _ => f) ∘ₗ (symGroupAction k V n σ).toLinearMap := by
  unfold symGroupAction
  apply LinearMap.ext
  intro x
  show (PiTensorProduct.reindex k (fun _ => V) σ) (PiTensorProduct.map (fun _ => f) x) =
    PiTensorProduct.map (fun _ => f) ((PiTensorProduct.reindex k (fun _ => V) σ) x)
  exact (PiTensorProduct.map_reindex (fun (_ : Fin n) => f) σ x).symm

/-- Permutation operators commute with diagonal operators:
for σ ∈ Sₙ and f ∈ End(V), σ ∘ f⊗ⁿ = f⊗ⁿ ∘ σ on V⊗ⁿ.
This gives symGroupImage ⊆ centralizer(diagonalActionImage). -/
theorem symGroupImage_le_centralizer_diagonalActionImage :
    symGroupImage k V n ≤ Subalgebra.centralizer k
      (diagonalActionImage k V n :
        Set (Module.End k (TensorPower k V n))) := by
  unfold symGroupImage
  apply Algebra.adjoin_le
  rintro x ⟨σ, rfl⟩
  simp only [SetLike.mem_coe, Subalgebra.mem_centralizer_iff]
  intro y hy
  unfold diagonalActionImage at hy
  have hcomm : ∀ g ∈ Set.range (fun (f : Module.End k V) =>
      PiTensorProduct.map (R := k) (fun (_ : Fin n) => f)),
      Commute (↑(symGroupAction k V n σ) : Module.End k (TensorPower k V n)) g := by
    rintro g ⟨f, rfl⟩
    exact symGroupAction_comm_diagonalAction k V n σ f
  exact (Algebra.commute_of_mem_adjoin_of_forall_mem_commute hy hcomm).symm.eq

/-- Diagonal operators commute with permutation operators:
diagonalActionImage ⊆ centralizer(symGroupImage). -/
theorem diagonalActionImage_le_centralizer_symGroupImage :
    diagonalActionImage k V n ≤ Subalgebra.centralizer k
      (symGroupImage k V n :
        Set (Module.End k (TensorPower k V n))) := by
  rw [Subalgebra.le_centralizer_iff]
  exact symGroupImage_le_centralizer_diagonalActionImage k V n

/-- The monoid homomorphism from `Equiv.Perm (Fin n)` to `End_k(V⊗ⁿ)` given by
the permutation action on tensor factors. -/
noncomputable def symGroupMonoidHom :
    Equiv.Perm (Fin n) →* Module.End k (TensorPower k V n) where
  toFun σ := (symGroupAction k V n σ).toLinearMap
  map_one' := by
    simp only [symGroupAction]
    apply LinearMap.ext; intro x
    change (PiTensorProduct.reindex k (fun _ => V) (Equiv.refl _)) x = x
    simp [PiTensorProduct.reindex_refl]
  map_mul' σ τ := by
    simp only [symGroupAction]
    apply LinearMap.ext
    intro x
    change (PiTensorProduct.reindex k (fun _ => V) (σ * τ)) x =
      (PiTensorProduct.reindex k (fun _ => V) σ)
        ((PiTensorProduct.reindex k (fun _ => V) τ) x)
    rw [show (σ * τ : Equiv.Perm (Fin n)) = τ.trans σ from rfl,
      ← PiTensorProduct.reindex_reindex]

/-- The algebra homomorphism from `k[Sₙ]` to `End_k(V⊗ⁿ)` lifting the permutation action. -/
noncomputable def symGroupAlgHom :
    MonoidAlgebra k (Equiv.Perm (Fin n)) →ₐ[k] Module.End k (TensorPower k V n) :=
  MonoidAlgebra.lift k (Module.End k (TensorPower k V n)) (Equiv.Perm (Fin n))
    (symGroupMonoidHom k V n)

/-- The range of the algebra homomorphism from `k[Sₙ]` equals `symGroupImage`. -/
theorem symGroupAlgHom_range :
    (symGroupAlgHom k V n).range = symGroupImage k V n := by
  unfold symGroupAlgHom symGroupImage
  apply le_antisymm
  · -- range ⊆ adjoin: every element in range is in adjoin
    rintro x ⟨f, rfl⟩
    induction f using Finsupp.induction_linear with
    | zero => exact Subalgebra.zero_mem _
    | add f g hf hg => rw [map_add]; exact Subalgebra.add_mem _ hf hg
    | single a b =>
      change (MonoidAlgebra.lift k _ _ (symGroupMonoidHom k V n)) (Finsupp.single a b) ∈ _
      rw [MonoidAlgebra.lift_single]
      exact Subalgebra.smul_mem _
        (Algebra.subset_adjoin (Set.mem_range.mpr ⟨a, by simp [symGroupMonoidHom]⟩)) _
  · -- adjoin ⊆ range: each generator is in range, and range is a subalgebra
    apply Algebra.adjoin_le
    rintro x ⟨σ, rfl⟩
    exact ⟨MonoidAlgebra.single σ 1, by
      simp [MonoidAlgebra.lift_single, symGroupMonoidHom]⟩

/-- The image of k[Sₙ] in End(V⊗ⁿ) is a semisimple ring.
This follows from Maschke's theorem: the group algebra k[G] is
semisimple when char(k) does not divide |G| (in char 0, always). -/
instance symGroupImage_isSemisimpleRing
    [CharZero k] :
    IsSemisimpleRing (symGroupImage k V n) := by
  rw [← symGroupAlgHom_range]
  haveI : NeZero (Nat.card (Equiv.Perm (Fin n)) : k) := by
    rw [Nat.card_perm, Nat.card_fin]
    exact ⟨Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero n)⟩
  exact (symGroupAlgHom k V n).toRingHom.rangeRestrict.isSemisimpleRing_of_surjective
    (symGroupAlgHom k V n).toRingHom.rangeRestrict_surjective

/-- V⊗ⁿ is a faithful module over symGroupImage when n ≤ dim V.
Distinct permutations produce distinct operators on V⊗ⁿ when
there are enough linearly independent vectors. -/
theorem symGroupImage_faithfulSMul
    (hN : n ≤ Module.finrank k V) :
    FaithfulSMul (symGroupImage k V n) (TensorPower k V n) := by
  constructor
  intro a b hab
  apply Subtype.ext
  apply LinearMap.ext
  intro x
  exact hab x

/-- The centralizer of the symmetric group image equals the diagonal
action image. This is the key content of Schur-Weyl duality:
every endomorphism of V⊗ⁿ commuting with all permutations is
a polynomial in diagonal operators.

**Proof approach (Etingof Theorem 5.18.2 + Lemma 5.18.3):**
The ≥ direction is `diagonalActionImage_le_centralizer_symGroupImage`.
For ≤: Via the basis `Basis.piTensorProduct`, an Sₙ-equivariant
endomorphism has matrix M[c,f] depending only on the multiset
{(c(i),f(i))}. The diagonal operator (map (fun _ => g)) has matrix
∏ᵢ g[c(i),f(i)]. Equality reduces to: the span of
{∏ᵢ g[c(i),f(i)] : g ∈ End V} over all g equals the space of
Sₙ-invariant matrices. This is the Veronese spanning property
(= Lemma 5.18.3(i): Sⁿ(U) is spanned by {u⊗ⁿ : u ∈ U}),
which holds in characteristic 0 by irreducibility of Sⁿ(U) as a
GL(U)-representation.

**Proof:** The ≤ direction uses the averaging/polarization argument from
Theorem 5.18.2: if φ commutes with all permutations, then conj_σ(φ) = φ
for all σ, so n!·φ = Σ_σ conj_σ(φ). By multilinear polarization
(Lemma 5.18.3), this sum lies in the fullDiagonalSubalgebra = diagonalActionImage.
Dividing by n! (char 0) gives φ ∈ diagonalActionImage.
-/
theorem centralizer_symGroupImage_eq_diagonalActionImage
    [CharZero k]
    (_hN : n ≤ Module.finrank k V) :
    Subalgebra.centralizer k
      (symGroupImage k V n :
        Set (Module.End k (TensorPower k V n))) =
    diagonalActionImage k V n := by
  apply le_antisymm
  · -- Hard direction: centralizer(Sₙ) ≤ diagonalActionImage
    -- Theorem 5.18.2 proves centralizer = UE.range via the chain:
    --   centralizer ≤ fullDiag ≤ diagSub ≤ UE.range ≤ centralizer
    -- We only need: centralizer ≤ fullDiag = diagonalActionImage
    -- Reproduce the centralizer ≤ fullDiag step from Theorem 5.18.2
    open Theorem5_18_2_Helpers in
    intro φ hφ
    rw [Subalgebra.mem_centralizer_iff] at hφ
    change φ ∈ Lemma5_18_3.fullDiagonalSubalgebra k V n
    -- φ commutes with all reindex(σ), so conj_σ(φ) = φ
    have hconj : ∀ σ : Equiv.Perm (Fin n),
        (PiTensorProduct.reindex k (fun _ => V) σ).toLinearMap * φ *
        (PiTensorProduct.reindex k (fun _ => V) σ).symm.toLinearMap = φ := by
      intro σ
      set e := PiTensorProduct.reindex k (fun _ => V) σ
      have hcomm := hφ e.toLinearMap (Algebra.subset_adjoin ⟨σ, rfl⟩)
      have he_inv : e.toLinearMap * e.symm.toLinearMap = 1 := by
        ext v; simp [Module.End.mul_eq_comp]
      calc e.toLinearMap * φ * e.symm.toLinearMap
          = φ * e.toLinearMap * e.symm.toLinearMap := by rw [hcomm]
        _ = φ * (e.toLinearMap * e.symm.toLinearMap) := by rw [mul_assoc]
        _ = φ * 1 := by rw [he_inv]
        _ = φ := mul_one _
    -- n! · φ = ∑_σ conj_σ(φ), and ∑_σ conj_σ(φ) ∈ fullDiag
    set fullDiag := Lemma5_18_3.fullDiagonalSubalgebra k V n
    have hfact : (n.factorial : k) ≠ 0 := Nat.cast_ne_zero.mpr n.factorial_ne_zero
    have hmem : φ ∈ Submodule.span k (Set.range fun f : Fin n → Module.End k V =>
        PiTensorProduct.map f) :=
      @map_span_eq_top k _ V _ _ n _ _ ▸ Submodule.mem_top
    have hsum := avg_conj_mem_fullDiag (k := k) (V := V) (n := n) φ hmem
    have heq : ∑ σ : Equiv.Perm (Fin n),
        (PiTensorProduct.reindex k (fun _ => V) σ).toLinearMap * φ *
        (PiTensorProduct.reindex k (fun _ => V) σ).symm.toLinearMap =
        (n.factorial : k) • φ := by
      simp_rw [hconj, Finset.sum_const, Finset.card_univ,
        Fintype.card_perm, Fintype.card_fin, ← Nat.cast_smul_eq_nsmul k]
    rw [heq] at hsum
    have := fullDiag.toSubmodule.smul_mem (n.factorial : k)⁻¹ hsum
    rwa [inv_smul_smul₀ hfact] at this
  · exact diagonalActionImage_le_centralizer_symGroupImage
      k V n

/-- Schur-Weyl duality, part (i): The images of k[S_n] and End_k(V)
in End(V^⊗n) are mutual centralizers.

Specifically, symGroupImage = centralizer(diagonalActionImage) and
diagonalActionImage = centralizer(symGroupImage).
(Etingof Theorem 5.18.4, part i) -/
theorem Theorem5_18_4_centralizers
    [CharZero k]
    (hN : n ≤ Module.finrank k V) :
    symGroupImage k V n = Subalgebra.centralizer k
      (diagonalActionImage k V n :
        Set (Module.End k (TensorPower k V n)))
    ∧ diagonalActionImage k V n = Subalgebra.centralizer k
      (symGroupImage k V n :
        Set (Module.End k (TensorPower k V n))) := by
  have h_cent := centralizer_symGroupImage_eq_diagonalActionImage k V n hN
  constructor
  · -- symGroupImage = centralizer(diagonalActionImage)
    -- By double centralizer theorem: centralizer(centralizer(symGroupImage)) = symGroupImage
    -- Since centralizer(symGroupImage) = diagonalActionImage, this gives the result
    haveI := symGroupImage_isSemisimpleRing k V n
    haveI := symGroupImage_faithfulSMul k V n hN
    rw [← h_cent]
    exact (Theorem5_18_1_double_centralizer k (TensorPower k V n) (symGroupImage k V n)).symm
  · -- diagonalActionImage = centralizer(symGroupImage)
    exact h_cent.symm

/-- Schur-Weyl duality, part (ii): The symmetric group and diagonal
action subalgebras of End(V^⊗n) are both semisimple.
(Etingof Theorem 5.18.4, part ii) -/
theorem Theorem5_18_4_semisimple
    [CharZero k]
    (hN : n ≤ Module.finrank k V) :
    IsSemisimpleRing (symGroupImage k V n)
    ∧ IsSemisimpleRing (diagonalActionImage k V n) := by
  constructor
  · exact symGroupImage_isSemisimpleRing k V n
  · -- diagonalActionImage = centralizer(symGroupImage)
    -- centralizer of semisimple subalgebra is semisimple
    rw [← centralizer_symGroupImage_eq_diagonalActionImage
      k V n hN]
    haveI := symGroupImage_isSemisimpleRing k V n
    haveI := symGroupImage_faithfulSMul k V n hN
    exact Theorem5_18_1_commutant_semisimple k (TensorPower k V n) (symGroupImage k V n)

/-- Schur-Weyl duality, part (iii): Decomposition of V^⊗n.

V^⊗n decomposes as a direct sum of tensor products of simple modules:
  V^⊗n ≅ ⊕_i S_i ⊗ L_i
where {S_i} are the distinct simple k[S_n]-modules (Specht modules)
appearing in V^⊗n and {L_i} are the corresponding irreducible
polynomial GL(V)-representations.
(Etingof Theorem 5.18.4, part iii) -/
theorem Theorem5_18_4_decomposition
    [CharZero k]
    (hN : n ≤ Module.finrank k V) :
    ∃ (ι : Type) (_ : Fintype ι) (_ : DecidableEq ι)
      (S : ι → Type (max u v)) (L : ι → Type u)
      (_ : ∀ i, AddCommGroup (S i))
      (_ : ∀ i, Module k (S i))
      (_ : ∀ i, AddCommGroup (L i))
      (_ : ∀ i, Module k (L i)),
      Nonempty (TensorPower k V n ≃ₗ[k]
        DirectSum ι (fun i => S i ⊗[k] L i)) := by
  haveI := symGroupImage_isSemisimpleRing k V n
  haveI := symGroupImage_faithfulSMul k V n hN
  obtain ⟨ι, hι, hι_dec, V', W', hV'_acg, hV'_mod,
    hV'_Amod, hV'_simp, hW'_acg, hW'_mod, ⟨e⟩⟩ :=
    Theorem5_18_1_decomposition k
      (TensorPower k V n) (symGroupImage k V n)
  exact ⟨ι, hι, hι_dec, V', W',
    hV'_acg, hV'_mod, hW'_acg, hW'_mod, ⟨e⟩⟩

/-- Schur-Weyl duality: partition-indexed decomposition of V^⊗n.
This refines `Theorem5_18_4_decomposition` by re-indexing the decomposition
by `Nat.Partition n`. Each summand `S p ⊗ L p` collects the components
from the generic decomposition that are assigned to partition `p`.
(Etingof Theorem 5.18.4, part iii) -/
theorem Theorem5_18_4_partition_decomposition
    [IsAlgClosed k] [CharZero k]
    (hN : n ≤ Module.finrank k V) :
    ∃ (S : Nat.Partition n → Type (max u v))
      (L : Nat.Partition n → Type u)
      (_ : ∀ p, AddCommGroup (S p))
      (_ : ∀ p, Module k (S p))
      (_ : ∀ p, AddCommGroup (L p))
      (_ : ∀ p, Module k (L p)),
      Nonempty (TensorPower k V n ≃ₗ[k]
        DirectSum (Nat.Partition n)
          (fun p => S p ⊗[k] L p)) := by
  -- Use the existing ι-indexed decomposition from Theorem 5.18.4(iii)
  obtain ⟨ι, hι, hι_dec, S', L', hS'_acg, hS'_mod, hL'_acg, hL'_mod, ⟨e⟩⟩ :=
    Theorem5_18_4_decomposition k V n hN
  -- Re-index: choose any function f : ι → Nat.Partition n, then group
  -- summands by fiber. Empty fibers contribute zero modules.
  haveI : Nonempty (Nat.Partition n) :=
    ⟨⟨Multiset.replicate n 1, fun {i} hi => by
      simp [Multiset.mem_replicate] at hi; omega,
      by simp⟩⟩
  let f : ι → Nat.Partition n := fun _ => Classical.arbitrary _
  -- Define S p as the fiber direct sum: ⊕_{i : f⁻¹(p)} (S' i ⊗ L' i)
  -- Define L p = k (so S p ⊗ k ≅ S p via TensorProduct.rid)
  let M : ι → Type (max u v) := fun i => S' i ⊗[k] L' i
  refine ⟨fun p => DirectSum {i : ι // f i = p} (fun j => M j.val),
          fun _ => k,
          inferInstance, inferInstance, inferInstance, inferInstance, ⟨?_⟩⟩
  -- Build the equivalence chain:
  -- V⊗ⁿ ≃ ⊕_ι M ≃ ⊕_{Σ p, fiber} M ≃ ⊕_p (⊕_fiber M) ≃ ⊕_p ((⊕_fiber M) ⊗ k)
  -- Step 2: re-index ⊕_ι M along the fiber equivalence
  have e₂ := DirectSum.lequivCongrLeft (R := k)
    (Equiv.sigmaFiberEquiv f).symm (M := M)
  -- Step 3+4: sigma curry then tensor with k
  -- sigmaLcurryEquiv : (R) → [Semiring R] → {ι} → {α : ι → Type} → {δ : (i : ι) → α i → Type} →
  --   [DecidableEq ι] → [AddCommMonoid] → [Module] →
  --   DirectSum (Σ x, α x) (fun i => δ i.1 i.2) ≃ₗ[R]
  --     DirectSum ι (fun i => DirectSum (α i) (fun j => δ i j))
  let e₃ := @DirectSum.sigmaLcurryEquiv k _ (Nat.Partition n)
    (fun p => {j : ι // f j = p})
    (fun p (j : {j : ι // f j = p}) => M j.val)
    _ (fun _ _ => inferInstance) (fun _ _ => inferInstance)
  -- Step 4: tensor with k via TensorProduct.rid
  let e₄ := DFinsupp.mapRange.linearEquiv (R := k)
    (fun p : Nat.Partition n => (TensorProduct.rid k
      (DirectSum {j : ι // f j = p} (fun j => M j.val))).symm)
  -- Now compose: V⊗ⁿ →[e] ⊕_ι M →[e₂] ⊕_Σ M →[e₃] ⊕_p(⊕_fiber M) →[e₄] ⊕_p(⊕_fiber M ⊗ k)
  exact e.trans (e₂.trans (e₃.trans e₄))

end Etingof
