import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
import Mathlib.Algebra.Lie.UniversalEnveloping

/-!
# Definition 2.12.1: Symmetric Algebra, Exterior Algebra, and Universal Enveloping Algebra

(i) The **symmetric algebra** SV of V is the quotient of TV by the ideal generated by
v ⊗ w - w ⊗ v.

(ii) The **exterior algebra** ∧V of V is the quotient of TV by the ideal generated by
v ⊗ v.

(iii) If V is a Lie algebra, the **universal enveloping algebra** U(V) of V is the quotient
of TV by the ideal generated by v ⊗ w - w ⊗ v - [v, w].

## Mathlib correspondence

All three are in Mathlib: `SymmetricAlgebra R M`, `ExteriorAlgebra R M`, and
`UniversalEnvelopingAlgebra R L`.
-/

/-- The symmetric algebra of a module, in the sense of Etingof Definition 2.12.1 (i).
This is `SymmetricAlgebra k V` in Mathlib. -/
abbrev Etingof.SymmetricAlgebraDef (k : Type*) (V : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] :=
  SymmetricAlgebra k V

/-- The exterior algebra of a module, in the sense of Etingof Definition 2.12.1 (ii).
This is `ExteriorAlgebra k V` in Mathlib. -/
abbrev Etingof.ExteriorAlgebraDef (k : Type*) (V : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] :=
  ExteriorAlgebra k V

/-- The universal enveloping algebra (coordinate-free), in the sense of
Etingof Definition 2.12.1 (iii). This is `UniversalEnvelopingAlgebra k L` in Mathlib. -/
abbrev Etingof.UniversalEnvelopingAlgebraCoordFree (k : Type*) (L : Type*) [CommRing k]
    [LieRing L] [LieAlgebra k L] :=
  UniversalEnvelopingAlgebra k L
