import Mathlib.Algebra.Lie.UniversalEnveloping

/-!
# Definition 2.9.9: Universal Enveloping Algebra

Let 𝔤 be a Lie algebra. The **universal enveloping algebra** U(𝔤) is the associative
algebra generated by the elements of 𝔤 with the defining relations
xᵢxⱼ - xⱼxᵢ = [xᵢ, xⱼ].

## Mathlib correspondence

This is `UniversalEnvelopingAlgebra R L`.
-/

/-- The universal enveloping algebra, in the sense of Etingof Definition 2.9.9.
This is `UniversalEnvelopingAlgebra k L` in Mathlib. -/
abbrev Etingof.UniversalEnvelopingAlgebraDef (k : Type*) (L : Type*) [CommRing k]
    [LieRing L] [LieAlgebra k L] :=
  UniversalEnvelopingAlgebra k L
