import Mathlib.Algebra.Lie.Basic
import Mathlib.Algebra.Lie.UniversalEnveloping

/-!
# Example 2.9.12: Universal Enveloping Algebra of sl(2)

The associative algebra U(sl(2)) is the algebra generated by e, f, h, with relations
  he − eh = 2e,  hf − fh = −2f,  ef − fe = h.

## Mathlib correspondence

Partial match. Mathlib has `UniversalEnvelopingAlgebra` but sl(2) as a specific Lie algebra
with generators and relations is not directly available as a concrete presentation.

## Formalization note

Stating the presentation of U(sl(2)) requires defining sl(2) as a Lie algebra and then
showing its universal enveloping algebra satisfies these relations.
-/

/-- The universal enveloping algebra U(𝔤) exists for any Lie algebra 𝔤.
For sl(2), this gives the algebra with generators e, f, h and the standard relations.
(Etingof Example 2.9.12) -/
example (k : Type*) [CommRing k] (L : Type*) [LieRing L] [LieAlgebra k L] :
    Algebra k (UniversalEnvelopingAlgebra k L) := inferInstance
