import Mathlib.Algebra.Lie.Basic
import Mathlib.Algebra.Lie.UniversalEnveloping

/-!
# Example 2.9.13: Universal Enveloping Algebra of the Heisenberg Lie Algebra

The algebra U(ℋ), where ℋ is the Heisenberg Lie algebra, is the algebra generated by
x, y, c with the relations:
  yx − xy = c,  yc − cy = 0,  xc − cx = 0.

Note that the Weyl algebra is the quotient of U(ℋ) by the relation c = 1.

## Mathlib correspondence

Partial match. Mathlib has `UniversalEnvelopingAlgebra` but the Heisenberg Lie algebra
is not defined in Mathlib. The connection to the Weyl algebra (quotient by c = 1) is
also not formalized.

## Formalization note

This requires defining the Heisenberg Lie algebra (3-dimensional, with basis x, y, c
where [x, y] = c and c is central) and relating its enveloping algebra to the Weyl algebra.
-/

/-- The universal enveloping algebra of the Heisenberg Lie algebra. The Weyl algebra
is the quotient U(ℋ)/(c − 1). (Etingof Example 2.9.13) -/
example (k : Type*) [CommRing k] (L : Type*) [LieRing L] [LieAlgebra k L] :
    Algebra k (UniversalEnvelopingAlgebra k L) := inferInstance
