import Mathlib.Algebra.Polynomial.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Example 2.3.14: Irreducible and Indecomposable Representations of k and k[x]

1. A = k. Since representations of A are simply vector spaces, V = A is the only irreducible
   and the only indecomposable representation.

2. A = k[x]. The irreducible finite dimensional representations are the 1-dimensional
   representations V_λ = k with ρ(x) = λ for λ ∈ k. The indecomposable finite dimensional
   representations are V_{λ,n} = kⁿ with ρ(x) = J_{λ,n} (Jordan blocks).

This example shows that an indecomposable representation need not be irreducible.

## Mathlib correspondence

Exact match for the algebraic infrastructure. Polynomial rings, irreducibility, and Jordan
normal form theory are available in Mathlib.
-/

/-- For A = k, the unique irreducible representation is k itself (1-dimensional).
(Etingof Example 2.3.14(1)) -/
example (k : Type*) [Field k] : IsSimpleModule k k := inferInstance

/-- Over an algebraically closed field k, every simple k[x]-module is 1-dimensional.
Equivalently, every maximal ideal of k[x] has quotient of k-dimension 1.
This is because k[x] is a PID, so maximal ideals are generated by irreducible
polynomials, which are linear over an algebraically closed field.
(Etingof Example 2.3.14(2)) -/
theorem Etingof.Example_2_3_14_polynomial_reps (k : Type*) [Field k] [IsAlgClosed k]
    (I : Ideal (Polynomial k)) [hmax : I.IsMaximal] :
    Module.finrank k (Polynomial k ⧸ I) = 1 := by
  set p := Submodule.IsPrincipal.generator I
  have hI : I = Ideal.span {p} := by
    rw [← Ideal.submodule_span_eq]; exact (Submodule.IsPrincipal.span_singleton_generator I).symm
  rw [hI, finrank_quotient_span_eq_natDegree]
  have hne : p ≠ 0 := by
    intro h
    have hbot : I = ⊥ := by rw [hI, h, Ideal.span_singleton_eq_bot]
    rw [hbot] at hmax
    have hXtop : Ideal.span {(Polynomial.X : Polynomial k)} = ⊤ :=
      hmax.1.2 _ (bot_lt_iff_ne_bot.mpr (mt Ideal.span_singleton_eq_bot.mp
        Polynomial.X_ne_zero))
    exact (Polynomial.irreducible_X (R := k)).1 (Ideal.span_singleton_eq_top.mp hXtop)
  have hprime : (Ideal.span {p}).IsPrime := by rw [← hI]; exact hmax.isPrime
  rw [Ideal.span_singleton_prime hne] at hprime
  have hirr : Irreducible p := hprime.irreducible
  have hdeg : p.degree = 1 := IsAlgClosed.degree_eq_one_of_irreducible (k := k) hirr
  rwa [Polynomial.degree_eq_natDegree hne, Nat.cast_eq_one] at hdeg
