import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.RingQuot
import Mathlib.LinearAlgebra.Basis.VectorSpace

/-!
# Proposition 2.7.1: Basis for the Weyl Algebra

(i) A basis for the Weyl algebra A is {xⁱyʲ, i, j ≥ 0}.
(ii) A basis for the q-Weyl algebra A_q is {xⁱyʲ, i, j ∈ ℤ}.

## Mathlib correspondence

No direct match. The Weyl algebra is not formalized in Mathlib. The proof uses representation
theory: linear independence is shown by constructing a faithful representation on
t^a k[a][t, t⁻¹] where x acts by multiplication by t and y acts by d/dt.

## Formalization note

We define the Weyl algebra as a quotient of the free algebra on two generators by the
relation yx - xy = 1 (i.e., yx = xy + 1). The q-Weyl algebra statement is omitted as it
requires invertible generators (a group algebra construction) which is a separate formalization
challenge.
-/

namespace Etingof

variable (k : Type*) [CommRing k]

/-- The generators of the Weyl algebra: `x` and `y`. -/
abbrev WeylGen := Fin 2

/-- The `x` generator of the Weyl algebra in the free algebra. -/
noncomputable abbrev weylX : FreeAlgebra k WeylGen := FreeAlgebra.ι k (0 : Fin 2)

/-- The `y` generator of the Weyl algebra in the free algebra. -/
noncomputable abbrev weylY : FreeAlgebra k WeylGen := FreeAlgebra.ι k (1 : Fin 2)

/-- The defining relation of the Weyl algebra: `y * x = x * y + 1`.
This encodes the commutation relation `[y, x] = 1`, or equivalently `yx - xy = 1`. -/
def WeylAlgebraRel : FreeAlgebra k WeylGen → FreeAlgebra k WeylGen → Prop :=
  fun a b => a = weylY k * weylX k ∧ b = weylX k * weylY k + 1

/-- The Weyl algebra over `k`, defined as `k⟨x, y⟩ / ⟨yx - xy - 1⟩`.
This is the associative `k`-algebra generated by `x` and `y` with the relation `yx = xy + 1`. -/
noncomputable abbrev WeylAlgebra : Type _ := RingQuot (WeylAlgebraRel k)

/-- The canonical map from the free algebra to the Weyl algebra. -/
noncomputable def WeylAlgebra.mk : FreeAlgebra k WeylGen →ₐ[k] WeylAlgebra k :=
  RingQuot.mkAlgHom k (WeylAlgebraRel k)

/-- The image of the `x` generator in the Weyl algebra. -/
noncomputable def WeylAlgebra.x : WeylAlgebra k := WeylAlgebra.mk k (weylX k)

/-- The image of the `y` generator in the Weyl algebra. -/
noncomputable def WeylAlgebra.y : WeylAlgebra k := WeylAlgebra.mk k (weylY k)

/-- The standard monomial `x^i * y^j` in the Weyl algebra. -/
noncomputable def WeylAlgebra.monomial (i j : ℕ) : WeylAlgebra k :=
  WeylAlgebra.x k ^ i * WeylAlgebra.y k ^ j

/-- **Proposition 2.7.1 (i)**: The standard monomials `{xⁱyʲ : i, j ≥ 0}` form a basis
for the Weyl algebra `A` over `k`.

More precisely, the function `(i, j) ↦ xⁱyʲ` from `ℕ × ℕ` to the Weyl algebra
is a basis for the Weyl algebra as a `k`-module. -/
theorem Proposition_2_7_1 :
    LinearIndependent k (fun p : ℕ × ℕ => WeylAlgebra.monomial k p.1 p.2) ∧
    ⊤ ≤ Submodule.span k (Set.range (fun p : ℕ × ℕ => WeylAlgebra.monomial k p.1 p.2)) := by
  sorry

end Etingof
